### ISSUE TITLE
Поступление. Узнавание ФИО по первым буквам

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#101]
![default](https://user-images.githubusercontent.com/40735638/42769292-6cfa6c5c-892a-11e8-9fd6-1f4032c68aa2.jpg)

**Comment by ekaterinacat** [comment]
При выборе из любого списка предлагать ФИО по первым буквам

**Comment by rdn1983** [comment]
Нужно выбрать любой список и набрать первые символы фамилии, например "Ко", тогда в списке будет выбрана фамилия "Кошкина"
