### ISSUE TITLE
Поступление. Убрать из обязательного поля номер истории болезни

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#107]
![default](https://user-images.githubusercontent.com/40735638/42770876-1012bef0-892e-11e8-9873-a8b95553ffa3.jpg)

**Comment by LuliLa** [comment]
Было выполнено в рамках другой задачи

**Comment by ekaterinacat** [comment]
Я помню, просто думала, что о ней забыли.

**Comment by ekaterinacat** [comment]
Сделано. Закрываем
