### ISSUE TITLE
Поступление. Добавить к  обязательным полям перечисленные графы

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#108]
![default](https://user-images.githubusercontent.com/40735638/42771082-ae177d98-892e-11e8-8932-c96020a48738.jpg)

**Comment by ekaterinacat** [comment]
Добавить к ** обязательным полям**  следующие поля:
1.ФИО, дежурный кардиореаниматолог, зав. кардиореанимации, дежурный врач РХМДиЛ и заведующий РХМДиЛ, дежурный анестезиолог

**Comment by Bsska** [comment]
Реализовано

**Comment by ekaterinacat** [comment]
Сделано
