### ISSUE TITLE
Добавить текст к "протоколу интубации"

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#111]
![default](https://user-images.githubusercontent.com/40735638/42771728-cd00aa84-8930-11e8-992f-d1f14c935e6c.jpg)

**Comment by ekaterinacat** [comment]
Вставить текст "В связи с неэффективностью консервативной терапии, нарастающей дыхательной и сердечно-сосудистой недостаточностью принято решение перевести больного на ИВЛ. После предварительной оксигенации лицевой маской больной интубирован с первой попытки трубкой № 9. Трубка фиксирована. Дыхание проводится во все отделы, симметрично. Налажена ИВЛ в режиме SIMV, ДО - 550 мл, FIO2- 30%, P ins 15 mbr, PEEP 5 mbr

**Comment by Bsska** [comment]
![image](https://user-images.githubusercontent.com/39027336/55910386-fd318f00-5be6-11e9-876f-02cd82d266a7.png)
