### ISSUE TITLE
Шаблоны-назначения

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#119]
![-](https://user-images.githubusercontent.com/40735638/43015255-caf71212-8c57-11e8-9240-2700b0f1592b.jpg)

**Comment by ekaterinacat** [comment]
При выборе шаблона (он должен "подсвечиваться") назначения должны ему соответствовать

**Comment by LuliLa** [comment]
Возникла та же проблема, что с шаблонами назначений в окне назначений. Не находятся лекарства, по ранее указанным данным

**Comment by ekaterinacat** [comment]
Простите, не поняла. Позвоните пожалуйста, когда удобно
--
Отправлено из Mail.Ru для Android воскресенье, 05 августа 2018г., 01:48 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
Принимается. Все хорошо
