### ISSUE TITLE
Назначения, ШАБЛОН . ОКС , продолжение

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#123]
![default](https://user-images.githubusercontent.com/40735638/43016059-429937e4-8c5a-11e8-886f-9cbe141dbc5f.jpg)

**Comment by LuliLa** [comment]
Опишите, пожалуйста, какие важные элементы есть на скриншоте, которые необходимо реализовать

**Comment by ekaterinacat** [comment]
1.  Лист назначений должен иметь самостоятел
![1](https://user-images.githubusercontent.com/40735638/43246282-d3f4146c-90b9-11e8-9e82-0ee4105442cf.jpg)
ьную вкладку:

**Comment by ekaterinacat** [comment]
![2](https://user-images.githubusercontent.com/40735638/43246335-049f6b7a-90ba-11e8-9c3c-e51e5422b5c3.jpg)

**Comment by ekaterinacat** [comment]
Затем нам предоставляется возможность выбора шаблона листа назначений или другие варианты

**Comment by ekaterinacat** [comment]
![3](https://user-images.githubusercontent.com/40735638/43246419-47c85a56-90ba-11e8-8ca9-b459d6ad50a4.jpg)

**Comment by ekaterinacat** [comment]
Сокращенный диагноз не связан ни с какими данными истории болезни, набирается вручную и должен "переноситься" от дня ко дню

**Comment by ekaterinacat** [comment]
![4](https://user-images.githubusercontent.com/40735638/43246497-804f623e-90ba-11e8-8aac-34b9c5f5f7cb.jpg)

**Comment by ekaterinacat** [comment]
Врач "вручную" выбирает кнопку "КАГ" и "без КАГ" и это также не связано с другими частями истории болезни

**Comment by ekaterinacat** [comment]
Варианты шаблонов могу написать по всем группам болезней. Они все  есть в "старой истории", но если нужно, то я пришлю

**Comment by ekaterinacat** [comment]
![5](https://user-images.githubusercontent.com/40735638/43246932-e31a470c-90bb-11e8-8501-6572b60a553a.jpg)

**Comment by ekaterinacat** [comment]
Вот такие наиболее часто употреляемые шаблоны  программа должна предлагать

**Comment by ekaterinacat** [comment]
![6](https://user-images.githubusercontent.com/40735638/43247061-413c6af4-90bc-11e8-95be-d9d696d21296.jpg)

**Comment by ekaterinacat** [comment]
Это - "шаблон ОКС при поступлении"

**Comment by ekaterinacat** [comment]
![7](https://user-images.githubusercontent.com/40735638/43247108-650520e8-90bc-11e8-8bf7-04bedbb47690.jpg)

**Comment by ekaterinacat** [comment]
Удобно, когда 
- "слева" находятся все группы препаратов, которые мы используем

**Comment by ekaterinacat** [comment]
![8](https://user-images.githubusercontent.com/40735638/43247264-da28537c-90bc-11e8-908f-cbcd5756f820.jpg)

**Comment by ekaterinacat** [comment]
Если в выбранном шаблоне нет ДОПОЛНИТЕЛЬНОГО нужного нам препарата, то мы имеем возможность в поле "группы" выбрать необходимую нам группу лекарств

**Comment by ekaterinacat** [comment]
![9](https://user-images.githubusercontent.com/40735638/43247449-63b32dd8-90bd-11e8-94de-e4fa37f61925.jpg)

**Comment by ekaterinacat** [comment]
То есть эту задачку не закрываем

**Comment by LuliLa** [comment]
Все описанные возможности реализованы для листов назначений.

**Comment by ekaterinacat** [comment]
Сделано. Спасибо. Закрываем
