### ISSUE TITLE
Назначения. Шаблоны. ХОБЛ

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#124]
![default](https://user-images.githubusercontent.com/40735638/43016183-b33782d0-8c5a-11e8-87cd-196a975e0d53.jpg)

**Comment by ekaterinacat** [comment]
Назначения в шаблоне "ХОБЛ"

**Comment by LuliLa** [comment]
![image](https://user-images.githubusercontent.com/6269330/43685757-7eada9ae-98c1-11e8-8ae3-87881b6ef855.png)

**Comment by ekaterinacat** [comment]
Прекрасно
--
Отправлено из Mail.Ru для Android воскресенье, 05 августа 2018г., 15:09 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
Замечательно
--
Отправлено из Mail.Ru для Android воскресенье, 05 августа 2018г., 15:09 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
![-1](https://user-images.githubusercontent.com/40735638/43992094-ef0ec718-9d81-11e8-8af1-a4c26b5ecde9.jpg)

**Comment by ekaterinacat** [comment]
Нет физраствора (см. "шаблоны")

**Comment by ekaterinacat** [comment]
отлично
