### ISSUE TITLE
Назначение. Шаблоны. Сердечная недостаточность

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#125]
![default](https://user-images.githubusercontent.com/40735638/43016250-f316f53e-8c5a-11e8-9808-3c937c7847d5.jpg)

**Comment by LuliLa** [comment]
![image](https://user-images.githubusercontent.com/6269330/43685805-8f7905d4-98c2-11e8-9e55-bb38e7946cb8.png)

**Comment by LuliLa** [comment]
Кнопочку НК переименовала в ПИКС/НК

**Comment by ekaterinacat** [comment]
![- 1](https://user-images.githubusercontent.com/40735638/43992038-01d1d12a-9d81-11e8-948e-ecc6166f49dd.jpg)

**Comment by ekaterinacat** [comment]
В шаблонах назначений ПИКС" ошибочно добавлены другие таблетки

**Comment by ekaterinacat** [comment]
![- 2](https://user-images.githubusercontent.com/40735638/43992060-542adc8c-9d81-11e8-80fe-072fe40994bb.jpg)

**Comment by ekaterinacat** [comment]
В назначениях (как отдельно вкладке) список таблеток правильный

**Comment by ekaterinacat** [comment]
Пожелание - 
1. можно ли "завернуть" таблетки на весь лист, чтобы не перелистывать
2. Можно ли установить "предпросмотр" для окончательного выверения таблеток перед печатью
