### ISSUE TITLE
Назначения, ШАБЛОН  ГБ

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#126]
![default](https://user-images.githubusercontent.com/40735638/43016371-44f2d1a2-8c5b-11e8-9ae8-574e9d827e47.jpg)

**Comment by LuliLa** [comment]
![image](https://user-images.githubusercontent.com/6269330/43220210-2fad0e20-9052-11e8-8221-44d754bc2463.png)


На данный момент окно назначений выглядит так. Здесь выл выбран шаблон НК

**Comment by ekaterinacat** [comment]
Вы правы, действительно выбран шаблон "НК". Но если выбрать ГБ... ситуация улучшается... Но не исправляется
![default](https://user-images.githubusercontent.com/40735638/43221026-3fecc45e-9054-11e8-9f9c-f0af6797fab4.jpg)

**Comment by ekaterinacat** [comment]
Это так, как выглядят назначения ГБ в моей версии программы (25.07)

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43991984-d6bb2b22-9d7f-11e8-95ed-0f379f4a54d8.jpg)

**Comment by ekaterinacat** [comment]
При открытии листа назначений ГБ:
1. Не хватает капельницы - физ раствор + магнезия (см.шаблон)
2. Нужно добавить раздел "бета-блокаторы"(слева), "метопролол 25 мг х 2 раза" (справа)

**Comment by ekaterinacat** [comment]
![- 1](https://user-images.githubusercontent.com/40735638/43992016-9b82f606-9d80-11e8-94dd-1ccdbdf8eb18.jpg)

**Comment by ekaterinacat** [comment]
Те же изменения необходимо внести во вкладку "назначения" (выделено черным овалом)

**Comment by ekaterinacat** [comment]
Отлично
