### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#127]
![default](https://user-images.githubusercontent.com/40735638/43016452-8ef410cc-8c5b-11e8-93a5-927cab23ec8b.jpg)

**Comment by ekaterinacat** [comment]
Не работают "письма на СМ", "Бланки"

**Comment by rdn1983** [comment]
kzkzkz

**Comment by rdn1983** [comment]
tttt

**Comment by ekaterinacat** [comment]
отлично
