### ISSUE TITLE
Список групп !! (Доработка вкладки Консилиум)

### ISSUE THREAD

**Issue by LuliLa** [rdn1983/cardiology#128]
Каждой группе "дежурный администратор ...", "кардиореаниматолог" соответствует список фамилий, из которых мы должны иметь возможность выбирать (этот список я пришлю
Наиболее часто используемые фамилии *зав отделения, зам. главного врача по терапии должны сразу "предлагаться" по умолчанию
Фамилия врача кардиореаниматолога должна "автоматически соответствовать ФИО врача, который стал заводить историю болезни

**Comment by LuliLa** [comment]
Список врачей отделения кардиореанимации:
Арсланбенкова Серминаз Махмудовна (Арсланбенкова С.М.)
Горячева Елена Владимировна (Горячева Е.В.)
Кошкина Екатерина Виленовна (Кошкина Е.В.)
Беспалова Юлия Эдуардовна (Беспалова Ю.Э.)
Миронова Елена Александровна (Миронова Е.А.)
Докторова Марина Викторовна (Докторова М.В.)
Балханова Анна Юрьевна (Балханова А.Ю.)
Баграмова Юлия Анатольевна (Баграмова Ю.А.)
Генералова Ольга Александровна (Генералова О.А.)
Щербакова Светлана Владимировна (Щербакова С.В.)
Кустова Татьяна Юрьевна (Кустова Т.Ю.)

Врачи отделения РХМДиЛ :
Самочатов Денис Николаевич, заведующий (Самочатов Д.Н.)
Комков Артем Андреевич (Комков А.А.)
Миленькин Борис Игоревич (Миленький Б.И.)
Потехин Дмитрий Александрович (Потехин Д.А.)
Мостовой Игорь Владимирович (Мостовой И.В.)
Шестов Д.В.

Врачи отделения анестезиологии

Костыря Ю.Е.
Данченко О.И.
Ерошин Н. И.
Магидин Д. В.
Шиганова А. М.
Капитанов А. Н.
Казамбаев Е. А.

Зам. главного врача по терапии - Арефьев А.А
Зав. центра анестезиологии и реанимации - Шкуратова Н.В.
Зав. центра хирургии - Покровский К.А.

Дежурные администраторы -

Арефьев А.А.
Алекперов С.Ф.
Горбунов А.Л.
Горячев В.И.
Додица А.Н.
Зинухов А.Ф.
Иванов А.Э.
Иванов Г.И.
Казамбаев Е.А.
Кисель Д.Ю.
Клименко А.А.
Конев Д.Е.
Костылев Г.Н.
Костыря Ю.Е.
Лоскутников М.А.
Магомедов Х.Р.
Мартынов П.А.
Пейкер А.Н.
Покровский К.А.
Резепов Н.А.
Релин В.Е.
Семенов А.Ю.
Семченко В.И.
Соболев В.В.
Шандалин В.А.
Ширшов И.А.
Юрьев А.А.

**Comment by rdn1983** [comment]
Списки людей на вкладке Консилиум - и в других местах - выровнены
