### ISSUE TITLE
Титул

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#143]
![-1](https://user-images.githubusercontent.com/40735638/43991312-cb630202-9d72-11e8-89a1-a8cb17f6b290.jpg)

**Comment by ekaterinacat** [comment]
1. Для выборе группы предлагать  ФИО (в коротком варианте, например, Магидин Д.В.) только входящих в группу
2. Наиболее часто повторяющийся товарищей (завед. обоих отделений) выбирать сразу

**Comment by LuliLa** [comment]
пункт 1. сделан в рамках другой задачи. отображаются только пользователи групп

**Comment by rdn1983** [comment]
Списки пользователей согласованы с Екатериной Виленовной
