### ISSUE TITLE
Консилиум

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#147]
![default](https://user-images.githubusercontent.com/40735638/43992589-31af590a-9d89-11e8-9948-2c0935eb2b9b.jpg)

**Comment by ekaterinacat** [comment]
При выборе "кнопки" ЦЕЛЬ ОПЕРАТИВНОГО ПОСОБИЯ в окошке "цель консилиума" появляется соответствующая запись

**Comment by ekaterinacat** [comment]
![1](https://user-images.githubusercontent.com/40735638/43992606-86a8b460-9d89-11e8-9590-9d85bee6dc18.jpg)

**Comment by ekaterinacat** [comment]
В графу диагноз вносится диагноз из первичного осмотра
![2](https://user-images.githubusercontent.com/40735638/43992625-db090582-9d89-11e8-854f-1ac8f71120c5.jpg)

**Comment by ekaterinacat** [comment]
Место в истории, откуда берется диагноз в "консилиум"

**Comment by rdn1983** [comment]
Диагноз - берется из первичного осмотра.
Цель консилиума - значение заполняется в зависимости от цели оперативного пособия
Решение - в зависимости от вариантов решения консилиума
Состав консилиума - сделать 3 человека по умолчанию

**Comment by ekaterinacat** [comment]
Принимается

**Comment by ekaterinacat** [comment]
![2018-09-08_21-07-20](https://user-images.githubusercontent.com/40735638/45257275-04bc5b80-b3ac-11e8-8ab6-5985e4d38a8a.png)

**Comment by ekaterinacat** [comment]
Вот так выглядит "собранный" консилиум, когда мы его выводим на печать.
Пожелания: 
- Все формочки при распечатывании должны быть написаны с красной строки
1. В "шапке" консилиума нужно поменять очередность участников (сначала - дежурный администратор, затем зам.главного врача, затем зав. отделением, потом - врачи)
2. В данном случае не удается напечатать дежурного администратора (несмотря на то, что "выбран" из списка
3. Если нет данных анализов крови, то нужно писать "анализы в работе". Если какие-то показатели в анализах не заполнены (то есть еще нет данных по этим анализам), то эти перечислять эти  показатели не нужно при печати
4. Данные рентгенографии не нужны в консилиуме
5. Все участники консилиума должны быть перечислены в конце, чтобы они могли расписаться

**Comment by ekaterinacat** [comment]
![1](https://user-images.githubusercontent.com/40735638/45771289-6357c400-bc4d-11e8-87c6-7a60f5abf1c4.jpg)

**Comment by ekaterinacat** [comment]
1. При распечатывании консилиума члены консилиума повторяются несколько раз
2. Объективный статус больного с "клинической смертью" соответствует шаблону "гипертоническая болезнь

**Comment by ekaterinacat** [comment]
3. Дежурный администратор
![2](https://user-images.githubusercontent.com/40735638/45771409-af0a6d80-bc4d-11e8-88e2-8cdebf32bbe8.jpg)

**Comment by ekaterinacat** [comment]
4. По прежнему неправильная очередность членов консилиума
5. Дежурный врач, который заполняет историю, автоматически должен стать членом консилиума и не выделяться в вордовском документе 
![3](https://user-images.githubusercontent.com/40735638/45771537-0dcfe700-bc4e-11e8-810e-ce86bb6f0b1d.jpg)

**Comment by ekaterinacat** [comment]
![4](https://user-images.githubusercontent.com/40735638/45771626-4374d000-bc4e-11e8-94b8-91e6461aca83.jpg)

**Comment by ekaterinacat** [comment]
Если анализы не заполнены, то пишется "Анализы - в работе". Нельзя писать анализы, данных которых нет

**Comment by ekaterinacat** [comment]
![5](https://user-images.githubusercontent.com/40735638/45771744-98184b00-bc4e-11e8-8725-205627b6d47b.jpg)

**Comment by ekaterinacat** [comment]
![6](https://user-images.githubusercontent.com/40735638/45771840-d877c900-bc4e-11e8-894e-89bc5c4e6819.jpg)

**Comment by ekaterinacat** [comment]
В закладки "варианты решения консилиума" добавить вкладку "ОКС с подъемом ST". Там должен быть текст "У больного с ОКС с подъемом ST" необходимо выполнить реваскуляризацию в экстренном порядке по жизненным показаниям

**Comment by Bsska** [comment]
Для "ОКС с подъемом ST" текст заполнен, по анализам замечания устранены. Войдет в следующий релиз

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/46571496-9eacff00-c97e-11e8-839b-0c9e12531596.png)

**Comment by Bsska** [comment]
исправлено
