### ISSUE TITLE
Первичный осмотр

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#148]
![1](https://user-images.githubusercontent.com/40735638/43992682-74aa108c-9d8a-11e8-8143-f922ee4788a9.jpg)

**Comment by rdn1983** [comment]
Органы пищеварения и мочевыделительная система не заполнены!!!

**Comment by LuliLa** [comment]
В старой версии не было заполнения этих полей по шаблону. Скиньте необходимые данные.

**Comment by ekaterinacat** [comment]
Из шаблона "ОКС" исчезла "нервная система"
![2018-09-08_19-04-03](https://user-images.githubusercontent.com/40735638/45256082-172d9980-b39a-11e8-9624-910c5f0219de.png)

**Comment by ekaterinacat** [comment]
А в другом шаблоне она есть
![2018-09-08_19-05-32](https://user-images.githubusercontent.com/40735638/45256115-8905e300-b39a-11e8-8989-a17d72c4fdf3.png)

**Comment by LuliLa** [comment]
Уровень сознания – ясное, продуктивному контакту доступна, менингиальные симптомы не выявляются, очаговой неврологической симптоматики нет. - правильно ли использовать вот этот шаблон для нервной системы при ОКС с подъемом?

**Comment by ekaterinacat** [comment]
Да, правильно

**Comment by ekaterinacat** [comment]
Все - отлично,принимается
