### ISSUE TITLE
Хронические заболевания

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#149]
![default](https://user-images.githubusercontent.com/40735638/43992871-a93b791e-9d8d-11e8-8310-ce76deb86241.jpg)

**Comment by ekaterinacat** [comment]
В графе хронические заболевания должны болезни из "списка" добавляться, их может быть много или не быть совсем (все зависит от степени болезненности субъекта)

**Comment by rdn1983** [comment]
У пациента может быть несколько заболеваний. 
При нажатии на добавление нового заболевания - не стирать предыдущее

**Comment by ekaterinacat** [comment]
Очень хорошо
