### ISSUE TITLE
Лист назначений "клиническая смерть"

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#151]
![default](https://user-images.githubusercontent.com/40735638/43993034-41e2c9f4-9d90-11e8-86d7-932e161a4c2a.jpg)

**Comment by ekaterinacat** [comment]
назначения неправильные

**Comment by LuliLa** [comment]
Пришлите, пожалуйста, еще разок правильные списки лекарств.

**Comment by ekaterinacat** [comment]
Сделано
