### ISSUE TITLE
Осмотр 2ой день

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#161]
![1](https://user-images.githubusercontent.com/40735638/43993420-9217dc5c-9d95-11e8-9bbe-8c0edc4d6d55.jpg)

**Comment by ekaterinacat** [comment]
Оформить обход во 2-ой день (если нет шаблона - пришлю). 
Внизу в зеленой рамке - добавить неизменную фразу "место установки венозного катетера без особенностей"

**Comment by ekaterinacat** [comment]
Вот так должен выглядеть осмотр на

**Comment by ekaterinacat** [comment]
![2018-09-08_17-31-42](https://user-images.githubusercontent.com/40735638/45255323-73d68780-b38d-11e8-9245-81bf425b5312.png)

**Comment by ekaterinacat** [comment]
Не работает закладка "осмотр на 2-ой день": вот так выглядет осмотр (он называется "утренний совместный осмотр") при выводе на печать
![2018-09-08_17-36-19](https://user-images.githubusercontent.com/40735638/45255349-daf43c00-b38d-11e8-821f-68dc3a014b50.png)

**Comment by ekaterinacat** [comment]
Хотела напомнить, что этот дневник - "дневник 2-ого дня". Комментарии к цифрам:
![2018-09-08_17-37-48](https://user-images.githubusercontent.com/40735638/45255398-7a193380-b38e-11e8-9d28-23548fad4e2e.png)

1. Диагноз должен выходить из последнего дневника предыдущего дня. Если была КАГ - то диагноз "после КАГ". Если не было КАГ - из скорректированного диагноза
2.

**Comment by ekaterinacat** [comment]
2. Динамика жалоб : стандартная фраза "На фоне терапии состояние улучшилось"
3. Объективно -  пишется стандартный дневник, чуть подробнее, чем обычно 
4. Заключение - Больной продолжает находится в ОКР для продолжения терапии

Таким образом, осмотр 2 дня выглядит как расширенных дневник, в котором находятся все обследования предыдущего дня и содержатся планы на текущее время и перспектива

**Comment by LuliLa** [comment]
Распишите пункт 3, пожалуйста. Чтобы я взяла текст и вставила)

**Comment by ekaterinacat** [comment]
Кажется, что это - тоже что и 179
