### ISSUE TITLE
Предоперационный эпикриз

### ISSUE THREAD

**Issue by rdn1983** [rdn1983/cardiology#173]
Отдельная форма для предоперационного эпикриза. На форме можно будет выбрать какие анализы, какие данные будут в итоговом отчете
Анамнез = Первичка
Диагноз = Первичка или дополнительно можно выбрать из Дневников (кнопочка)
Данные дополнительных исследований = Первчика или анализы (кровь и ЭКГ)
Вызов формы добавить в Действия

**Comment by ekaterinacat** [comment]
диагноз, который выносится в предоперационный эпизкриз должен по умолчанию находится в выделенном окне. Затем, если нужно, мы должны иметь возможность редактировать
![2018-09-08_14-31-40](https://user-images.githubusercontent.com/40735638/45253708-619c1f80-b374-11e8-8e28-337ac0986faa.png)

**Comment by ekaterinacat** [comment]
![2018-09-08_14-36-29](https://user-images.githubusercontent.com/40735638/45253721-afb12300-b374-11e8-9d5a-d5b4247cf256.png)

**Comment by ekaterinacat** [comment]
Анамнез берется из первички .... но из графы ANAMNESIS MORBI 
![2018-09-08_14-40-29](https://user-images.githubusercontent.com/40735638/45253759-657c7180-b375-11e8-9d13-af33dcda0748.png)

**Comment by ekaterinacat** [comment]
я была невнимательна, так как оказалась "анамнезов" несколько

**Comment by ekaterinacat** [comment]
![2018-09-08_15-03-32](https://user-images.githubusercontent.com/40735638/45253982-6bc01d00-b378-11e8-83a0-ab930b192516.png)

**Comment by ekaterinacat** [comment]
При попытке сохранить данные анализов мочи "выскакивает" вот такое окно

**Comment by ekaterinacat** [comment]
![2018-09-08_15-05-41](https://user-images.githubusercontent.com/40735638/45254010-b477d600-b378-11e8-800a-55537f9f8443.png)

**Comment by ekaterinacat** [comment]
![2018-09-08_15-10-41](https://user-images.githubusercontent.com/40735638/45254062-edfd1100-b379-11e8-9308-9bffe10ca494.png)

**Comment by ekaterinacat** [comment]
При добавлении анализов "выскакивает" это окно ... Зачем?

**Comment by ekaterinacat** [comment]
Если анализы от одного и того же числа, то нужно предлагать написать "время", а то надпись "текущие" анализы всех запутает

**Comment by ekaterinacat** [comment]
![2018-09-08_15-16-20](https://user-images.githubusercontent.com/40735638/45254082-55b35c00-b37a-11e8-905e-5b0d93fe6afe.png)

**Comment by ekaterinacat** [comment]
![Uploading 2018-09-08_15-20-05.png…]()

**Comment by ekaterinacat** [comment]
![Uploading 2018-09-08_15-20-05.png…]()

**Comment by ekaterinacat** [comment]
![Uploading 2018-09-08_15-21-01.png…]()

**Comment by ekaterinacat** [comment]
![2018-09-08_15-23-49](https://user-images.githubusercontent.com/40735638/45254249-e475a800-b37d-11e8-9250-dfc9eb17ef18.png)

**Comment by ekaterinacat** [comment]
![2018-09-08_15-51-12](https://user-images.githubusercontent.com/40735638/45254325-205d3d00-b37f-11e8-81c3-25e168903564.png)

**Comment by ekaterinacat** [comment]
1. В поле "дополнительные анализы" мы договаривались писать название анализов, которые мы внесли. Другие параметры "холестерин" "АСТ" и прочее (как на скриншоте) - писать не надо. Лучше автоматически заносить "другие анализы - в работе

**Comment by ekaterinacat** [comment]
В графе "группа крови"  по умолчанию писать - в работе. Если есть данные,  то их нужно переносить в текст. 
![2018-09-08_15-54-58](https://user-images.githubusercontent.com/40735638/45254382-c5781580-b37f-11e8-96a7-8d7a85b042b9.png)

**Comment by ekaterinacat** [comment]
![2018-09-08_15-57-09](https://user-images.githubusercontent.com/40735638/45254391-ed677900-b37f-11e8-8659-5a5749203d3a.png)

**Comment by ekaterinacat** [comment]
Диагноз должен выходить из первичного осмотра
![2018-09-08_15-58-31](https://user-images.githubusercontent.com/40735638/45254400-1982fa00-b380-11e8-871f-b87c773aa427.pn

**Comment by ekaterinacat** [comment]
![2018-09-08_15-58-31](https://user-images.githubusercontent.com/40735638/45254407-3ae3e600-b380-11e8-9099-5e5fa264c51c.png)

**Comment by ekaterinacat** [comment]
В этих графах должен быть:
1. По умолчанию зав. отделения РХМДиЛ "Самочатов Д.Н."
2. Дежурный анестезиолог (он выбирается при первичном осмотре, если он не выбран, то вписывается заведующий отделением Кострыря Ю.Е.)

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/45763656-9a23df00-bc39-11e8-844b-46b776883625.jpg)

**Comment by ekaterinacat** [comment]
Нет соответствия между диагнозом и его обоснованием

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/45763823-fedf3980-bc39-11e8-9239-3fb7dc71e6d1.jpg)

**Comment by ekaterinacat** [comment]
Диагноз в предоперационный эпикриз должен вставляться "автоматически" и при этом мы его должны видеть еще до распечатывания для возможности коррекции

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/45766441-47015a80-bc40-11e8-8aba-d97ad83ccf21.jpg)

**Comment by ekaterinacat** [comment]
1. В графе "группа крови" должны быть информация только - "группа крови ... Резус фактор ...Фенотип ... " Все остальное должно находиться в графе "данные лабораторных исследований"
2. В графе - показания к операции должно быть написано "Верификация состояния коронарных артерий"
