### ISSUE TITLE
Выпадающие списки людей

### ISSUE THREAD

**Issue by rdn1983** [rdn1983/cardiology#176]
На основе механизма групп сделать разные списки людей в выпадающих списках

**Comment by ekaterinacat** [comment]
Я присылала списки  и группы

**Comment by ekaterinacat** [comment]
Уже описано, но не сделано

**Comment by ekaterinacat** [comment]
Группы нет
![image](https://user-images.githubusercontent.com/40735638/52521489-e1fadf80-2c88-11e9-894d-fab1daef9b51.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/52521497-05be2580-2c89-11e9-8476-159dee32ffdd.png)

**Comment by ekaterinacat** [comment]
Группы нет
![image](https://user-images.githubusercontent.com/40735638/52521512-37cf8780-2c89-11e9-9fe1-2231488a8b43.png)

**Comment by ekaterinacat** [comment]
Группы нет
![image](https://user-images.githubusercontent.com/40735638/52521537-75ccab80-2c89-11e9-91be-20483047b80c.png)
