### ISSUE TITLE
Распечатка дневников

### ISSUE THREAD

**Issue by rdn1983** [rdn1983/cardiology#179]
Из форм дневников и из формы истории болезни реализовать возиожность распечатать отчет дневников

**Comment by ekaterinacat** [comment]
![2018-09-08_20-04-19](https://user-images.githubusercontent.com/40735638/45256677-83ac9680-b3a2-11e8-97ad-79b7039f8142.png)

**Comment by ekaterinacat** [comment]
1. При добавлении дневника поле пустое (обведено большим овалом)
2. Время последнего дневника "неактивно", поэтому не выводится на печать

**Comment by ekaterinacat** [comment]
![2018-09-08_20-07-01](https://user-images.githubusercontent.com/40735638/45256700-d38b5d80-b3a2-11e8-8c10-077c366f2606.png)

**Comment by ekaterinacat** [comment]
Так выглядит вывод в ворд дневников после КАГ:
1. Нет диагноза
2. Нет осмотра хирурга
3. нет окончания дня

**Comment by ekaterinacat** [comment]
![2018-09-15_20-01-08](https://user-images.githubusercontent.com/40735638/45588734-312f2500-b922-11e8-8cdb-e0d4835aa2d7.png)

**Comment by ekaterinacat** [comment]
1. Эта надпись появляется при попытки распечатать дневники после КАГ
2. После попытки "сохранить" программа сама закрывается и надо опять ее открывать через win RAR

**Comment by ekaterinacat** [comment]
Пожелания:
1 (Оранжевый полукруг) поле нужно увеличить за счет уменьшения поля дневника (фиолетового полукруга, цифра 2)
3. Если данные Данные ЧД, АД, ЧСС, Рs , внесены в закладке (в нашем случае "Дневники после КАГ"), то они должны по умолчанию предлагаться в последующих дневниках,при этом сохраняются возможности корректировки
4. Поле по умолчанию должно содержать запись "Динамика инфаркта миокарда"

Самые большие поля должны быть "Диагноз", "Результатат КАГ", осмотр на 8.05

**Comment by ekaterinacat** [comment]
По результатам сегодняшней работы:
1. Не получается законченного документа "Дневники после КАГ", который должен включать:
- Прием больного из операционной
-  "шаблонный" осмотр деж. врача ОКР с данными КАГ и диагнозом
- осмотр дежурного хирурга
- последующая серия дневников до 8.05
- финальный дневник в 8.05, который содержит: "шаблонный осмотр", перечисление всего того, что с больным делали на протяжении суток (диагноз, результат КАГ, анализы, осмотры специалистов, данные рентгена и т.д. .... )
2. Не получается запоминать сделанные исправления и не удается распечатывать с учетом измененного шаблоны

P.S. 
- Можно убрать окошко "PS" (это значит, ПУЛЬС) из всех дневников навсегда
- Везде слово "больной" нужно заменить на пациент
- Сделать возможность случайного выбора ЧД, ЧСС и АД из выбранного диапазона
- Сделать результат выбора из диапазона "обязательным" для последующих дневников внутри настоящего дня

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/45761877-cdfd0580-bc35-11e8-8566-1aa7f3c5696c.jpg)

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/45761961-000e6780-bc36-11e8-9306-7de521de7eb2.jpg)

**Comment by ekaterinacat** [comment]
Закладка "дневники"
1. Если выбираются для распечатывания дневники, то время следующего дневника должно быть на 4 часа больше, чем предыщущее (19.09.18 17.55; 19.09.18 21.55; 20.09.18 1.55 и т.д.)
2. Если в одном дневнике уже есть ЧД, АД, ЧДД, то аналогичные цифры (в пределах выбранного диапазона) должны быть предложены по умолчанию

**Comment by ekaterinacat** [comment]
Раздроблю
