### ISSUE TITLE
Смена шаблонов певички

### ISSUE THREAD

**Issue by rdn1983** [rdn1983/cardiology#185]
При изменении шаблонов первички спрашивать пользователя, уверен ли он, что хочет изменить шбаблон

**Comment by ekaterinacat** [comment]
При редактировании шаблонов  первички (включающие полный шаблон) программа спрашивает "действительно ли нужно поменять шаблон" ... И тогда меняется весь шаблон. Это - правильно. 
Но важно иметь возможность внутри шаблона менять кусочки, которые относятся к другому шаблону
![2018-09-08_16-10-07](https://user-images.githubusercontent.com/40735638/45254516-3f110300-b382-11e8-9868-4aeba18cc647.png)

**Comment by ekaterinacat** [comment]
1. Сменить "кусочек" шаблоны
2. выбрать какой именно шаблон вставить
3. Уточнить "действительно ли это нужно ?.... "

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/45767255-55507600-bc42-11e8-887c-d0470afcf672.jpg)

**Comment by ekaterinacat** [comment]
Нужно, чтобы 
1. Было понятно, к какому больному принадлежит этот шаблон 
![jpg](https://user-images.githubusercontent.com/40735638/45767347-9e082f00-bc42-11e8-9bd9-0d589a9978f3.jpg)

**Comment by ekaterinacat** [comment]
2. Чтобы если вносятся изменения в уже готовый шаблон, он исправлялся "кусочками", а не весь целиком
