### ISSUE TITLE
Отложенная КАГ

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#190]
![2018-09-08_19-58-31](https://user-images.githubusercontent.com/40735638/45256618-b609c400-b3a1-11e8-8669-1912ac7c4309.png)

**Comment by ekaterinacat** [comment]
Дневники пустые

**Comment by LuliLa** [comment]
текст отличается от других видов дневников?

**Comment by ekaterinacat** [comment]
Ничем не отличается 

C уважением , Кошкина Е. В.

**Comment by ekaterinacat** [comment]
[Васидов, ОКС без подъема ST.docx](https://github.com/rdn1983/cardiology/files/2612530/ST.docx)

**Comment by ekaterinacat** [comment]
Пациент | Васидов   М.Х 66 лет
-- | --
Поступил   в стационар | 24.11.18
Жалобы | на   момент осмотра на  слабость
Диагноз | ИБС:  острый коронарный   синдром без элевации сегмента ST. Гипертоническая болезнь III ст, риск   высокий. Сахарный диабет 2 типа, субкомпенсация. Эпилепсия.
Анамнез | Anamnеsis morbi: Длительно страдает гипертонической болезнью   с максимальным повышением АД до 200/120 мм.рт.ст., регулярно принимает   амлодипин 10 мг. Перенес инфаркт миокарда в 2016 году, КАГ не проводилась   (мед.документаций не предоставлено). Последние несколько месяцев отмечает   снижение  толерантности к физическим   нагрузкам, одышку, дискомфорт в грудной клетке. 24.11.18 в связи с   возобновлением вышеописанных жалоб самостоятельно обратился в ОКР ГКБ №67,   госпитализирован.
Данные   объективного исследования | Общий   осмотр:   Состояние  средней тяжести. Положение  в постели активное. T тела  36.5◦С. Кожные покровы  и видимые слизистые бледно-розовые, кожа   теплая, умеренной влажности, целостность    кожи не нарушена. Периферических отеков нет. Телосложение   правильное,  нормостеническое.   Лимфатические узлы доступные пальпации не увеличены. Органы дыхания: Грудная   клетка правильной формы. ЧД 16-18 в минуту. Ход ребер обычный, межреберные   промежутки не расширены. Перкуторно: границы лёгких не изменены, лёгочный   звук с 2-х сторон. Аускультативно – дыхание жесткое, проводится во все   отделы, хрипов нет. Голосовое дрожание одинаковое на симметричных участках   грудной клетки. Сердечно-сосудистая система: Область сердца не изменена.   Верхушечный толчок кнутри от средне-ключичной линии, не визуализируются.   Границы относительной тупости сердца –увеличены на 2 см кнаружи вверх и влево   от левой среднеключичной линии. Шумы-не высл. АД 165/80 мм рт.ст, ЧСС-PS–57,   ритм правильный, удовлетворительного наполнения и напряжения. Органы   пищеварения: Язык влажный. Живот мягкий, при глубокой пальпации   безболезненный. Перистальтика выслушивается. Шум трения брюшины, а также   систолический шум над аортой и мезентериальными артериями отсутствуют.   Перитонеальных симптомов нет. Селезёнка не пальпируется. Печень пальпируется   у края реберной дуги. Стул регулярный, последний 23.11. Мочевыделительная   система: Поясничная область при осмотре не изменена. Почки не пальпируются.   Симптом поколачивания по поясничной области безболезненно с двух сторон.   Дизурии нет.  Нервная система: Уровень   сознания - ясное, продуктивному контакту доступна, менингиальные симптомы не   выявляются, очаговой неврологической симптоматики нет.
Данные   дополнительного исследования | ЭКГ –   Синусовый ритм. ЧСС 82 в минуту. Нормальное положение ЭОС. Признаки   гипертрофии ЛЖ.   Клинический   анализ крови от 24.11: гем-161 г/л, эрит-5,2 млн/мкл, лейк-7,9 тыс/мкл,   тромб-183 тыс/мкл.   Биохимический   анализ крови от 24.11: КФК-65 Ед/л, креатинин 77,5 мкмоль/л, холестерин 4,6   ммоль/л, глюкоза 6,3 ммоль/л.
Группа   крови |  
Показания   к операции | Острый   коронарный синдром  без  элевации сегмента ST
Цель   операции | Реваскуляризация   миокарда
Противопоказания | Абсолютных   и относительных противопоказаний нет
Планируемое   оперативное пособие | Коронарография,   по результатам которой при необходимости возможно выполнение ангиопластики
Возможные   осложнения | Кровотечение   из места пункции, гематома, инфаркт миокарда, диссекция аорты и артерий,   ложная аневризма, инфаркт мозга, почечная недостаточность
Вид обезболивания | в/в   анестезия
  |  
Операционная   бригада | Миленкин   Б.И
Лечащий   врач | Арсланбекова   С.М.
Деж.   администратор | Дорожкин   ВВ.
Дата | 24.11.18

**Comment by ekaterinacat** [comment]
15:20  Осмотр дежурного врача ОКР Арсланбековой С.М. совместно с ангиохирургом Миленкиным Б.И.   
Больной доставлен из рентгеноперационной в сопровождении анестезиолога. 
При осмотре -  состояния средней тяжести,   ангинозных болей на момент осмотра нет. 
Жалобы на общую слабость. Больная в сознании, контактна, адекватна. Кожные покровы сухие, чистые. Над легкими аускультативно: дыхание жесткое, ослабленное в нижних отделах. ЧД 17 в мин. Тоны сердца приглушены, ритмичные. ЧСС 62  в мин. АД  126/80 мм рт.ст. Живот обычной формы; мягкий. Область пункции без особенностей. Признаков гематомы нет. Пульсация на конечностях адекватная.
По монитору синусовый ритм. 
КАГ: ЛКА:  Ствол ЛКА: не изменен
ПМЖВ: на границе проксимального и среднего сегментов стенозирована на 80% далее имеет неровные контуры. 1 ДВ – мелкая ветвь – в устье стенозирована на 50%, далее имеет неровные контуры. 2 ДВ – в устье стенозирована на 90%, далее имеет неровные контуры. 
ИВ: крупная ветвь- в средней трети стенозирована на 90%, далее имеет неровные контуры. 
ОВ: в проксимальной трети имеет неровные контуры, в средней трети стенозирована на 90%, далее имеет неровные контуры. 1 ВТК – мелкая ветвь - в средней трети стенозирована на 70%, далее имеет неровные контуры.  2 ВТК – мелкая ветвь - в проксимальной трети стенозирована на 70%, далее имеет неровные контуры. 3 ВТК – мелкая ветвь – имеет неровные контуры на всем протяжении.     
ПКА: в среднем сегменте окклюзирована, постокклюзионный отдел хорошо заполняется по внутри- и межсистемным коллатералям.
Заключение КАГ №1910: Выявлено многососудистое поражений коронарных артерий. критический стеноз.
Выполнено: Стентирование ОВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием). Стентирование ИВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием). Стентирование ПМЖ стентом  Endeavor Resolute 3,0х30 мм (с лекарственным покрытием)
ИБС:  Нестабильная стенокардия. Стентирование ОВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием), ИВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием), ПМЖ стентом  Endeavor Resolute 3,0х30 мм (с лекарственным покрытием) от 24.11.2018г. Гипертоническая болезнь III ст, риск высокий. Сахарный диабет 2 типа, субкомпенсация. Эпилепсия.

                                                                                                Врач                                      Арсланбекова С.М.

                                                                                                 Врач                                   Миленькин Б.И


16:50 Осмотр ренгеноваскулярного хирурга Миленькина Б.И  
Жалоб на момент осмотра не предъявляет. Объективно: Над легкими аускультативно: дыхание жесткое, ослабленное в нижних отделах. ЧД 17 в мин. Тоны сердца приглушены, ритмичные. ЧСС 61  в мин. PS 61 в мин. АД  130/80 мм рт ст. Живот обычной формы; безболезненный. 
Область пункции без особенностей. Признаков гематомы нет. Пульсация на конечностях адекватная.
                                                                                                           Врач Миленькин Б.И


20:55 Состояние стабильное,   ангинозные боли за время наблюдения не рецидивировали. Беспокоит общая слабость. 
Объективно: Над легкими аускультативно: дыхание жесткое, ослабленное в нижних отделах. ЧД 17 в мин. Тоны сердца приглушены, ритмичные. ЧСС 67 в мин. PS 67 в мин. АД  125/80 мм рт ст. Живот обычной формы; безболезненный. 
По монитору – синусовый ритм.

Врач                                      Арсланбекова С.М.

23:05 Больной спит. Объективно: Над легкими аускультативно: дыхание жесткое, ослабленное в нижних отделах. ЧД 17 в мин. Тоны сердца приглушены, ритмичные. ЧСС 65  в мин. PS 65 в мин. АД  130/80 мм рт ст. Живот обычной формы; безболезненный. 
Область пункции без особенностей. Признаков гематомы нет. Пульсация на конечностях адекватная.
                                                                                                       
Врач                                      Арсланбекова С.М.

25.11.2018 04:05
Состояние стабильное,   ангинозные боли за время наблюдения не рецидивировали. Больной спит.
Объективно: Над легкими аускультативно: дыхание жесткое, ослабленное в нижних отделах. ЧД 17 в мин. Тоны сердца приглушены, ритмичные. ЧСС 67  в мин. PS 67 в мин. АД  125/80 мм рт ст. Живот обычной формы; безболезненный. 
По монитору – синусовый ритм.

Врач                                      Арсланбекова С.М.
                            
07:25 Состояние стабильное. Ангинозные боли после КАГ и стентирования не рецидивировали. Беспокоит общая слабость. 
Объективно: Над легкими аускультативно: дыхание жесткое, ослабленное в нижних отделах. ЧД 17 в мин. Тоны сердца приглушены, ритмичные. ЧСС 68  в мин. PS 68 в мин. АД  120/70 мм рт ст. Живот обычной формы; безболезненный.
Рентгенография легких: умеренный пневмосклероз.
КАГ: Заключение КАГ №1910: Выявлено многососудистое поражений коронарных артерий. критический стеноз.
Выполнено: Стентирование ОВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием). Стентирование ИВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием). Стентирование ПМЖ стентом  Endeavor Resolute 3,0х30 мм (с лекарственным покрытием).
По монитору – синусовый ритм.
Диурез 1200 мл.
Область пункции без особенностей. Признаков гематомы нет. Пульсация на конечностях адекватная.

Врач                                      Арсланбекова С.М.






24.11.18. 
Переводной эпикриз.

Больной Васидов М.Х., 66 лет  находился  в ОКР с  24.11.18 с диагнозом: 
ИБС:  Нестабильная стенокардия. Стентирование ОВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием), ИВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием), ПМЖ стентом  Endeavor Resolute 3,0х30 мм (с лекарственным покрытием) от 24.11.2018г. Гипертоническая болезнь III ст, риск высокий. Сахарный диабет 2 типа, субкомпенсация. Эпилепсия.
На фоне проводимой терапии состояние стабильное. Ангинозные приступы после КАГ и стентирования не рецидивировали. Жалобы на общую слабость.
Объективно: Состояние средней степени тяжести. Кожные покровы физиологической окраски, теплые, влажные. Периферических отеков нет. В легких дыхание жесткое, проводится во все отделы, хрипов нет ЧД 16 в минуту. Тоны сердца приглушены, ритм правильный ЧСС 63 в минуту, АД 115\80мм.рт.ст. живот при пальпации мягкий, безболезненный. Мочится самостоятельно.
На ЭКГ: Синусовый ритм с ЧСС 69 уд/мин. Без отрицательной динамики.
Клинический анализ крови от 24.11: гем-161 г/л, эрит-5,2 млн/мкл, лейк-7,9 тыс/мкл, тромб-183 тыс/мкл.
Биохимический анализ крови от 24.11: КФК-65 Ед/л, креатинин 77,5 мкмоль/л, холестерин 4,6 ммоль/л, глюкоза 6,3 ммоль/л.
Рентген легких: умеренный пневмосклероз. 
Больной консультирован эндокринологом, даны рекомендации.
КАГ: Заключение КАГ №1910: Выявлено многососудистое поражений коронарных артерий. критический стеноз.
Выполнено: Стентирование ОВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием). Стентирование ИВ стентом Endeavor Resolute 2,75х18 мм (с лекарственным покрытием). Стентирование ПМЖ стентом  Endeavor Resolute 3,0х30 мм (с лекарственным покрытием).
Периферический катетер удален, место пункции без признаков воспаления. 
В области пункции артерии признаков воспаления и гематомы нет. 
Повязка снята.  Пульсация на конечности адекватная.
Для дальнейшего лечения и наблюдения больной переводится в кардиологическое отделение. 

Рекомендовано:
Tab. Aspirin 125 мг вечером
Tab. Zilti 75 мг х 1 раз в сутки
Tab. Nolpaza 20 мг вечером
Tab. Lozapi 50 мг х 1 р/д, утро
Tab Amlodipini 5 мг, вечер
Tab. Атorvasatini 20 мг, вечер
Tab. Veroshpironi 25 мг, утром

Врач Арсланбекова С.М.

**Comment by LuliLa** [comment]
В итоге делаем так: отложенные дневники и обычные храним в одном контейнере. при нажатии на кнопку вызывается менюшка с выбором какие именно дневники создаем(отложенные КАГ или обычные) если создается дневник отложенной КАГ, то автоматически добавляются 2 дневника. 1.-все плохо, 2 - через 15 мин , все хорошо.

**Comment by ekaterinacat** [comment]
Формально, до первого закрытия набранного текста все отлично получилось ... потом вот что происходит (сейчас попробую проиллюстрировать)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/50337090-21c30780-0521-11e9-99de-b06bb50684a8.png)

**Comment by ekaterinacat** [comment]
Это - я создала и сохранила, а когда иду в раздел программки
![image](https://user-images.githubusercontent.com/40735638/50337188-6cdd1a80-0521-11e9-8725-65b727b122b3.png)

**Comment by ekaterinacat** [comment]
То вижу кучу созданных дневников, открывая которые я не получаю документы, который я создавала.

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/50337281-a3b33080-0521-11e9-810e-fec6661de898.png)

**Comment by ekaterinacat** [comment]
Сохраняется только один дневничок... Тоже самое получается при попытки распечатывания.

**Comment by ekaterinacat** [comment]
Таким образом, отложенная КАГ с дневниками получилась прекрасно. Но  при закрытии документа, происходит дробление всего документа на "исходные" дневники

**Comment by ekaterinacat** [comment]
Кроме того, 
![image](https://user-images.githubusercontent.com/40735638/50337554-8a5eb400-0522-11e9-9492-eead3cab74cf.png)

**Comment by ekaterinacat** [comment]
Необходимо организовать последовательность между ПОСЛЕДНИМ обычным дневником   и дневником  ОТЛОЖЕННОЙ КАГ (разница между ними должна быть 1 час), а у нас получается 4 (как в типичных дневниках)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/50337745-18d33580-0523-11e9-9de2-0c532b2a4f26.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/51791021-0eedc380-21ae-11e9-99e8-0d933daff5f0.png)

**Comment by ekaterinacat** [comment]
Позволю себе напомнить просьбу от 24.11:
НеСМОТРЯ на наличие специальной вкладки "отложенная  КАГ" порядок должен быть всегда один и тот же
1. "Все нормально, обычный дневник" (за 1 час до начала болей)
2. Начинаются боли
3. Через 15 минут они купируются
4. Через полчаса проводится консилиум с решением о КАГ

**Comment by ekaterinacat** [comment]
см. переписку от 24.11. 
11:25
Беспокоит общая слабость. Ангинозные боли не рецидивируют.
Объективно: Над легкими аускультативно: дыхание жесткое, ослабленное в нижних отделах. ЧД 17 в мин. Тоны сердца приглушены, ритмичные. ЧСС 67 в мин. PS 67 в мин. АД 130/80 мм рт ст. Живот обычной формы; безболезненный.
ЭКГ монитор синусовый ритм

Врач Арсланбекова С.М.

**12:25** (ПРИБЛИЗИТЕЛЬНО ЧЕРЕЗ ЧАС ПОСЛЕ НОРМАЛЬНОГО ДНЕВНИКА С ХОРОШИМ САМОЧУВСТВИЕМ)
Жалобы на дискомфорт в грудной клетке, чувство нехватки воздуха, беспокоит общая слабость. Объективно: Над легкими аускультативно: дыхание жесткое, ослабленное в нижних отделах. ЧД 18 в мин. Тоны сердца приглушены, ритмичные. ЧСС 84 в мин. PS 84 в мин. АД 125/80 мм рт ст. Живот обычной формы; безболезненный.
По монитору – синусовый ритм. Назначено нитроглицерин 2,0 мл/ч в/в

Врач Арсланбекова С.М.

**12:40** (**12.25 + 15 МИНУТ, то  ЕСТЬ ЧЕРЕЗ ЧАС ПОСЛЕ НАЧАЛА БОЛЕЙ**)
Состояние тяжелое, ангинозные боли не беспокоят, беспокоит общая слабость.
Объективно: Над легкими аускультативно: дыхание жесткое, ослабленное в нижних отделах. ЧД 18 в мин. Тоны сердца приглушены, аритмичные. ЧСС 70 в мин. PS 70 в мин. АД 130/80 мм рт ст. Живот обычной формы; безболезненный.
По монитору – синусовый ритм.

Врач Арсланбекова С.М.

**"13.10 (12.40+30 минут) то есть через полчаса после предыдущего дневника)"** 
КОНСИЛИУМ в составе деж администратора Дорожкин В.В. ангиохирурга Миленкина Б.И., деж. врачей ОКР Арсланбековой С.М. и Баграмовой Ю.А
**Цель консилиума: определение показаний к КАГ. и ЧКВ.**

**Comment by ekaterinacat** [comment]
Прекрасно
