### ISSUE TITLE
Переименование закладки

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#192]
![2018-09-08_20-24-22](https://user-images.githubusercontent.com/40735638/45256881-44cc1000-b3a5-11e8-8403-703d47a9638a.png)

**Comment by ekaterinacat** [comment]
Переименовать "дневники без КАГ" в "дневники"

**Comment by rdn1983** [comment]
Переименовал
![image](https://user-images.githubusercontent.com/38911304/55793056-b484b380-5aca-11e9-9212-0f1de9fbbca9.png)
