### ISSUE TITLE
Замена "больной/больная" на "ПАЦИЕНТ"

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#198]
Во всей истории болезни нужно заменить  "больной/больная" на "ПАЦИЕНТ", чтобы не утруждаться склонением и спряжением

**Comment by Bsska** [comment]
сделано

**Comment by ekaterinacat** [comment]
Сегодня описала и привела примеры, где эта задача еще не доделана

**Comment by LuliLa** [comment]
а можете повторить примеры сюда в комментарии? Не нашла у нас в переписке по этому поводу ничего
