### ISSUE TITLE
Create form UserFormTrombolizis

### ISSUE THREAD

**Issue by rdn1983** [rdn1983/cardiology#20]
Create form UserFormTrombolizis

**Comment by rdn1983** [comment]
1. в кнопке Дата - нет слова Сегодня, как в исходнике
2. Для даты и времени - в VS использовать DateTimePicker

**Comment by LuliLa** [comment]
Исправила

**Comment by LuliLa** [comment]
![trombolisis](https://user-images.githubusercontent.com/6269330/39858490-6e1528ea-543f-11e8-97b7-7656b3065e04.png)
