### ISSUE TITLE
Лист назначений

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#222]
![image](https://user-images.githubusercontent.com/40735638/45927596-44ec1400-bf3e-11e8-9f36-f81ec9d7c25f.png)

**Comment by ekaterinacat** [comment]
если лист назначений, соответствует какому-то шаблону, то необходимо делать этот шаблон "активным"

**Comment by LuliLa** [comment]
А если , например, изначально врач выбрал готовый шаблон Я_ШАБЛОН1, но убрал парочку препаратов и парочку добавил своих, то этот лист назначений уже не имеет шаблона или по старой памяти мы считаем, что он Я_ШАБЛОН1?

**Comment by ekaterinacat** [comment]
Вопрос интересный ... 
Может быть можно оставлять "кнопку" ярко окрашенной, если шаблон остался неизменный и Оставить "окантовку", если на основе его произведены изменения... ?!

**Comment by LuliLa** [comment]
Сейчас сделала подсветку последнего выбранного вида шаблона. Отдельный вид подсветки для измененного шаблона оставила для следующего релиза

**Comment by ekaterinacat** [comment]
Отлично
