### ISSUE TITLE
Поступление пациента

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#252]
![image](https://user-images.githubusercontent.com/40735638/46241386-6e36f500-c3c1-11e8-802c-a3443c305470.png)

![image](https://user-images.githubusercontent.com/40735638/46241383-58293480-c3c1-11e8-9b47-133a631c1b9d.png)

**Comment by ekaterinacat** [comment]
Нет возможность просматривать и редактировать "поступление" пациента

**Comment by Bsska** [comment]
Поступление пациента открывается двойным щелчком по строке в таблице главного окна

**Comment by ekaterinacat** [comment]
Отлично получилось
