### ISSUE TITLE
Первичка

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#254]
После предварительного диагноза 
![image](https://user-images.githubusercontent.com/40735638/46241493-64ae8c80-c3c3-11e8-9747-b375a78a741d.png)

**Comment by ekaterinacat** [comment]
Добавить поле: "Назначено". По умолчанию добавить текст: 
1.	Стол **### ОВД/ НКД** (должно меняться)
 Режим постельный;
2.	ОАК, ОАМ; Ht; Мочевина, креатинин, электролиты, билирубин, общий белок, альбумины, ХС, ТГ; АЧТВ;
3.	АЛТ,АСТ, КФК, КФК-МВ,;
4.	ЭКГ; 
5.	Rg-графия органов грудной клетки- исключить застой в МКК;
6.	 Мониторинг АД, ЧСС, ЭКГ, t;
7.	Установка венозного катетера, обработка места его стояния 1%р-ром йодопирона, с последующим промыванием его антикоагулянтами после каждой внутривенной инъекции.

**Comment by ekaterinacat** [comment]
[ПИКС, шаблон.txt](https://github.com/rdn1983/cardiology/files/2430321/default.txt)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/46241566-5ca31c80-c3c4-11e8-961c-a1b66ecbdb80.png)

**Comment by ekaterinacat** [comment]
Вот так это выглядит

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/48970753-28915400-f021-11e8-9881-002fe6170f6b.png)

**Comment by ekaterinacat** [comment]
Вот что получается при распечатке...

**Comment by rdn1983** [comment]
1. Выбрать любого пациента из списка;
2. Выбрать пункт меню "Действия" -> "Открыть историю болезни"
3. В форме "История болезни" выбрать пункт меню "Действия" -> "Первичный обход"
4. Перейти на вкладку "Назначения"
5. Выбрать любой шаблон, например "ДЭП"
6. Снова выбрать любой шаблон, например "ДЭП"

ОШИБКА1: При повторном выборе того-же шаблона выскакивает окошко предупреждения о смене шаблона;
