### ISSUE TITLE
Шаблон "ОКС", 2 

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#271]
![image](https://user-images.githubusercontent.com/40735638/48967256-b738ad80-efee-11e8-8887-a22b113cdcb7.png)

![image](https://user-images.githubusercontent.com/40735638/48967231-6b860400-efee-11e8-8e59-78e545980263.png)

**Comment by ekaterinacat** [comment]
При выводе на печать шаблона ОКС без подъема ST обоснование принадлежит другому шаблону (ОКС с подъемом ST")

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/51790938-b4a03300-21ac-11e9-9388-40e7fc0b367c.png)

**Comment by ekaterinacat** [comment]
Получилось хорошо, только уберите, пожалуйста **ST** (артефакт из другого текста)

**Comment by nik-novozhilov** [comment]
Исправил текст в шаблоне.

**Comment by ekaterinacat** [comment]
НЕ исправилось

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/52518994-80754980-2c65-11e9-907f-b9f390a2ae6b.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/52518998-8ec36580-2c65-11e9-8a5a-00983bb6a94b.png)

**Comment by ekaterinacat** [comment]
Сделано, неактуально

**Comment by YuliYur** [comment]
http://joxi.ru/5mdBebot3vdDyA
ST не убрали

**Comment by rdn1983** [comment]
При применении шаблона "ОКС без подъема ST" в поле "Обоснование" убрал слово "ST" вначале
