### ISSUE TITLE
Шаблон ДЭП

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#285]
![image](https://user-images.githubusercontent.com/40735638/48968062-c6255d00-effa-11e8-81b8-5f44e53c040e.png)

**Comment by ekaterinacat** [comment]
1. Добавить кнопку с обоснованием "ДЭП"
2. Привязать к этому обоснованию следующий текст" Учитывая диагноз, сопутствующую патологию, пациенту показана ноотропная,  антикоагулянтная, диуретическая, ритмоурежеющая, гастропротективная терапия. настоящая терапия обоснована и соответствует стандартам лечения дисциркуляторным нарушениям, нарушениям ритма и проводимости, а также гипертонической болезни". 
3. Автоматически предлагать обоснование "ДЭП" при выборе общего шаблона "ДЭП"

**Comment by nik-novozhilov** [comment]
Выполнено, текст шаблона обновил.

**Comment by ekaterinacat** [comment]
Прекрасно, принимается
