### ISSUE TITLE
исправление больной - пациент

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#288]
![image](https://user-images.githubusercontent.com/40735638/48969138-579ccb00-f00b-11e8-9de2-9ed92b3f5118.png)

**Comment by ekaterinacat** [comment]
Была уже заведена задача переправки слов "больной" на пациент... Везде, где бы мы не использовали слово "больной"

**Comment by LuliLa** [comment]
исправлено в рамках другой таски
