### ISSUE TITLE
Выбор врача (связано с 162)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#301]
![image](https://user-images.githubusercontent.com/40735638/48970325-ed405680-f01b-11e8-9a35-bc0692b1cbe0.png)

**Comment by ekaterinacat** [comment]
Если уже выбран ответственный врач (Кошкина), то в других дневниках он "автоматически предлагается

**Comment by LuliLa** [comment]
Если выбрать врача до добавления нового дневника, то врач также указывается для следующего дневника. Скорее всего, дубликат более ранней задачи

**Comment by ekaterinacat** [comment]
Понятно

**Comment by ekaterinacat** [comment]
Обсуждено
