### ISSUE TITLE
Переключение на 12-часовой формат (связано с 162)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#303]
![image](https://user-images.githubusercontent.com/40735638/48970378-8f603e80-f01c-11e8-9337-33f7018ef9d7.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/48970393-bae32900-f01c-11e8-9c3e-30cb2a894bca.png)

**Comment by ekaterinacat** [comment]
Использование переключения на 12-часовой формат бессмысленно. 
Лучше здесь иметь возможность вручную проставить время, если это нужно

**Comment by rdn1983** [comment]
Если кликнуть на поле мышкой, то можно вручную задать время (часы и минуты)

**Comment by ekaterinacat** [comment]
Отлично
