### ISSUE TITLE
Распечатка дневников (связано с 162)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#304]
![image](https://user-images.githubusercontent.com/40735638/48970467-7e63fd00-f01d-11e8-80ad-f2291abb316a.png)

**Comment by ekaterinacat** [comment]
1. Скрытые дневники выводятся на печать
2. ФИО выбранных врачей не соответствуют тем ФИО, которые выводятся на печать

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/48970481-c1be6b80-f01d-11e8-8a27-759f04a6e45a.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/51791379-15cb0500-21b3-11e9-8240-1c8a0a6507b9.png)

**Comment by ekaterinacat** [comment]
Врач не выбран, а при печати врач появляется

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/51791394-3abf7800-21b3-11e9-96c8-16279dafe9b0.png)

**Comment by ekaterinacat** [comment]
1 Внутри истории болезни "ВРАЧ" почти всегда имеется ввиду "КАРДИОРЕАНИМАТОЛОГ"
2. При формировании дневников всегда должен предлагаться (по умолчанию) врач, заполнявший историю болезни
3. В выпадающем меню должен быть СПИСОК только докторов данного направления (например, анестезиолог, врач-кардиореаниматолог)

**Comment by nik-novozhilov** [comment]
по пунктам:
1. Переименовывать "ВРАЧ" на "КАРДИОРЕАНИМАТОЛОГ" не будем по договоренности.
2. При инициализации выпадающего списка значение по умолчанию заполняется автоматически лечащим врачом пациента.
3. В выпадающих списках при создании журнала КАГ, список врачей заполняется врачами из группы "Кардиореаниматологи" (duty_cardioreanim).

**Comment by ekaterinacat** [comment]
1. - согласна, мы договорились
2 и 3 - предлагаю оставить до лучших времен (я сегодня заведу короткие задачки по этому пункту), иначе мы никуда не сдвинемся
