### ISSUE TITLE
Не переносится диагноз в ежедневный осмотр (связано с 237)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#311]
![image](https://user-images.githubusercontent.com/40735638/48970933-3694a400-f024-11e8-951d-08d626b7fcb7.png)

![image](https://user-images.githubusercontent.com/40735638/48970923-2250a700-f024-11e8-9cb7-df7527e452ae.png)

**Comment by ekaterinacat** [comment]
Еще актуально

**Comment by LuliLa** [comment]
не воспроизводится
