### ISSUE TITLE
Взаимосвязь между КАГ и выводом в Word

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#335]
![image](https://user-images.githubusercontent.com/40735638/52523723-71ae8700-2ca5-11e9-833c-37cd06c9cdb2.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/52523798-38c2e200-2ca6-11e9-9858-8a768cf89ab6.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/52523825-92c3a780-2ca6-11e9-8cc1-c4cb4985c560.png)

**Comment by YuliYur** [comment]
Действия- открыть историю болезни- Анализы( Каг, кровь, экг) в ворд не выводятся через кнопку печать. Выходит чистый лист.

![image](https://user-images.githubusercontent.com/49306602/58053437-37843980-7b60-11e9-8b0a-e80a17d04ff9.png)

**Comment by toolkas** [comment]
У анализов в истории болезни нет отдельной печатной формы. Анализы выводятся из форм в составе других печатных форм. 
Не ошибка

**Comment by ekaterinacat** [comment]
Комментарий принимается. См. новую задачу 522
