### ISSUE TITLE
Случайный выбор ЧД, ЧСС, АД (согласно таблице)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#336]
Сделать возможность случайного выбора ЧД, ЧСС и АД из выбранного диапазона во всех вариантах дневников 

![image](https://user-images.githubusercontent.com/40735638/52523876-5f354d00-2ca7-11e9-857d-9b86c75c817f.png)

**Comment by ekaterinacat** [comment]
Вот здесь почему-то нет
![image](https://user-images.githubusercontent.com/40735638/52523888-aa4f6000-2ca7-11e9-8c8c-576f3f8ed9ae.png)

**Comment by ekaterinacat** [comment]
И в обосновании "отложенной КАГ" нет 
![image](https://user-images.githubusercontent.com/40735638/52523896-bfc48a00-2ca7-11e9-8355-0f62e4d3a40e.png)

**Comment by ekaterinacat** [comment]
Только вот здесь есть 
![image](https://user-images.githubusercontent.com/40735638/52523912-e8e51a80-2ca7-11e9-8a96-00f112020685.png)

**Comment by ekaterinacat** [comment]
Табличку надо использовать эту
![image](https://user-images.githubusercontent.com/40735638/52523917-02866200-2ca8-11e9-8eb5-223b3955d307.png)

**Comment by LuliLa** [comment]
Добавила выбор с помощью этой таблички в остальные дневники

**Comment by YuliYur** [comment]
![image](https://user-images.githubusercontent.com/49306602/56459490-11bb1780-639d-11e9-9a11-76a496c26bdc.png)

**Comment by YuliYur** [comment]
![image](https://user-images.githubusercontent.com/49306602/56459886-e509fe80-63a2-11e9-95c6-d0495a55e210.png)
