### ISSUE TITLE
Зав отделения в "назначениях"

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#339]
![image](https://user-images.githubusercontent.com/40735638/52524274-47ac9300-2cac-11e9-902a-0c47a214199b.png)

**Comment by ekaterinacat** [comment]
По умолчанию зав отделения (имеется ввиду наше отделение) - Кошкина ЕВ, остальные сотрудники отделения (кардиореанимации) могут быть выбраны при необходимости

**Comment by rdn1983** [comment]
Сделано так:
Кошкина
Миронова
все остальные
