### ISSUE TITLE
При редактировании поступления пациента в отчестве сохраняется фамилия, не меняется пол на женский, не сохраняется " Было КАГ"

### ISSUE THREAD

**Issue by Bsska** [rdn1983/cardiology#345]
1. Поступление пациента, изменить фамилию, нажать сохранение. Открыть заново. в графе " отчество" появляется введённая фамилия. 
2.  Поступление пациент, изменить пол на женский, сохранить, снова открыть. Пол остаётся мужской.
http://joxi.ru/E2ppQPLT9dMzZ2
3. Поступление пациент, выбрать "Было КАГ", сохранить, снова открыть. Значение не изменилось 
![image](https://user-images.githubusercontent.com/39027336/54953569-9ad75e00-4f59-11e9-8ff2-d62998e2bcfb.png)

**Comment by YuliYur** [comment]
Первые две ошибки исправились. Третья " Было КАГ" так и не сохраняется
http://joxi.ru/KAxJaPXCZ4jYym

**Comment by rdn1983** [comment]
"не было КАГ" и "было КАГ" удалены, так-как не несут смысловую нагрузку в этой форме
