### ISSUE TITLE
Документация, показания к тромболизису. Не выбирается лечащий врач

### ISSUE THREAD

**Issue by Bsska** [rdn1983/cardiology#348]
Документация,протоколы манипуляций, показания к тромболизису. Не корректно заполнен список лечащих врачей

![image](https://user-images.githubusercontent.com/39027336/54952837-f86aab00-4f57-11e9-9ed4-48ed445fdf0e.png)     При выборе любой строки и нажатии Ms Word появляется ошибка

http://joxi.ru/zAN6vR4CBb0jPA

**Comment by YuliYur** [comment]
Документация,протоколы манипуляций, показания к тромболизису.  Ошибка открытия ворда,
![image](https://user-images.githubusercontent.com/49306602/55628417-4f267f00-57b9-11e9-9866-1afc3eeb58fd.png)

**Comment by ekaterinacat** [comment]
Сделанор
