### ISSUE TITLE
Документация, бланки, ошибка при выборе любого бланка.

### ISSUE THREAD

**Issue by Bsska** [rdn1983/cardiology#349]
![image](https://user-images.githubusercontent.com/39027336/54953325-05d46500-4f59-11e9-8e7b-637517587246.png)

![image](https://user-images.githubusercontent.com/39027336/54953356-184e9e80-4f59-11e9-97a3-ed001669e3e0.png)

**Comment by nik-novozhilov** [comment]
Запилил посты билды для копирования папки шаблонов, попробуй запулиться и запустить приложение. Шаблоны должны открываться.

**Comment by ekaterinacat** [comment]
НЕ открываются

**Comment by nik-novozhilov** [comment]
Прошу проверить, сейчас бланки открываются.

**Comment by YuliYur** [comment]
http://joxi.ru/Rmzo3P5CY0Ezk2

В вордовский документ переносится только имя пациента, а не Ф.И.О

**Comment by YuliYur** [comment]
![image](https://user-images.githubusercontent.com/49306602/56077921-8a910100-5dea-11e9-9c2c-0f1c21c64ea2.png)
Тоже, только имя, а не ФИО

**Comment by YuliYur** [comment]
![image](https://user-images.githubusercontent.com/49306602/56078068-3129d180-5dec-11e9-8cee-855ca3d3edc2.png)
![image](https://user-images.githubusercontent.com/49306602/56078087-84038900-5dec-11e9-997a-74c5a8acc606.png)
![image](https://user-images.githubusercontent.com/49306602/56078095-a3021b00-5dec-11e9-954e-e47fc5041479.png)
![image](https://user-images.githubusercontent.com/49306602/56078117-ef4d5b00-5dec-11e9-8454-9b35ab307e5f.png)
![image](https://user-images.githubusercontent.com/49306602/56078118-0e4bed00-5ded-11e9-9aa9-f4e93849e71e.png)
![image](https://user-images.githubusercontent.com/49306602/56078126-215ebd00-5ded-11e9-8ed5-01716abbe986.png)

**Comment by LuliLa** [comment]
Исправлено, перепроверить на новом архиве
