### ISSUE TITLE
" Протокол алкосвидетельства". В протоколе не сохраняются изменения

### ISSUE THREAD

**Issue by Bsska** [rdn1983/cardiology#350]
Действия, история болезни, действия, первичный осмотр, " алкоголь употреблял", появляется кнопка " протокол алкосвидетельства ". В протоколе не сохраняются изменения. Ошибка в слове алкоОсвидетельство

![image](https://user-images.githubusercontent.com/39027336/54954071-d292d580-4f5a-11e9-92b4-e1c434fddc08.png)

**Comment by YuliYur** [comment]
Ошибка в слове алкоОсвидетельство не исправлена

**Comment by YuliYur** [comment]
![image](https://user-images.githubusercontent.com/49306602/56078204-0c365e00-5dee-11e9-88d5-21b3768af83d.png)
Протокол алко освидетельствования не открывается и не редактируется

**Comment by LuliLa** [comment]
Это уже сделано, но у тебя старая версия релиза
