### ISSUE TITLE
В ежедневном обходе не сохраняются ЭКГ, Рентген и Заключение специалистов

### ISSUE THREAD

**Issue by Bsska** [rdn1983/cardiology#353]
1. Действия, история болезни, ежедневный обход, анализы, рентген пустое окно  и не сохраняется.
![image](https://user-images.githubusercontent.com/39027336/55275711-0e32f400-52fb-11e9-87f0-522a45ffac2a.png)

2. Действия, история болезни,ежедневный обход, анализы: УЗИ не сохраняется в ежедневном осмотре, но появляются  при сохранении в самой истории болезни
![image](https://user-images.githubusercontent.com/39027336/55275648-10488300-52fa-11e9-81ac-ba65cee1e6e6.png)

3. Действия, история болезни,ежедневный обход, анализы: Заключения специалистов в ежедневном осмотре не сохраняются, только в самой истории болезни появляется.
![image](https://user-images.githubusercontent.com/39027336/55275675-76cda100-52fa-11e9-97d0-fb3172965e12.png)

**Comment by LuliLa** [comment]
По причине открытия таски все сделано, пожелания о множественной привязке одних и тех же анализов к разным обходам заведена отдельная таска
