### ISSUE TITLE
История болезни, в данных доп исследований нет кнопки " сохранить"

### ISSUE THREAD

**Issue by Bsska** [rdn1983/cardiology#354]
Действия, история болезни,действия, предоперационный эпикриз, данные доп исследований нет кнопки " сохранить"
![image](https://user-images.githubusercontent.com/39027336/55275825-02483180-52fd-11e9-8591-e7a8a3e1a208.png)

**Comment by LuliLa** [comment]
они ее тут и не просили. Просили, чтобы, если вот нажали распечатать, то сохранялось это в историю болезни. Спросить надо у Виленовны не передумала ли она

**Comment by rdn1983** [comment]
Закрываю
