### ISSUE TITLE
При выборе протокола констатации смерти открывается окно реанимационные мероприятия

### ISSUE THREAD

**Issue by YuliYur** [rdn1983/cardiology#355]
Документация, Протоколы манипуляции, констатация смерти, выходит протокол "Реанимационные мероприятия"
![image](https://user-images.githubusercontent.com/49306602/55629309-8f86fc80-57bb-11e9-8b04-c674d217395c.png)

![image](https://user-images.githubusercontent.com/49306602/55629334-9f9edc00-57bb-11e9-9298-30754357966f.png)

**Comment by rdn1983** [comment]
При констатации смерти и реанимационных мероприятиях вызываются одинаковые окошки - так и задумано

**Comment by ekaterinacat** [comment]
Прекрасно
