### ISSUE TITLE
Не показывается протокол алко-освидетельствования после повторного открытия окна первичного осмотра

### ISSUE THREAD

**Issue by YuliYur** [rdn1983/cardiology#356]
Действия, история болезни, первичный осмотр, редактировать.  Окно Данные первичного осмотра. "Алкоголь употреблял". Появляется окно " Протокол алко-освидетельствования" Заполняем, сохраняем, закрываем. При повторном открывании окна  " Данные первичного осмотра" протокол не появляется. Сначала надо нажать " Алкоголь употреблял"

![image](https://user-images.githubusercontent.com/49306602/55636746-31164a00-57cc-11e9-8cd2-0eea908e9c01.png)

**Comment by rdn1983** [comment]
Эти кнопки нужны только для того, чтобы не вводить руками одинаковый текст, пока не будем считать это поведение ошибкой

**Comment by ekaterinacat** [comment]
Ошибка продолжается
