### ISSUE TITLE
Неправильные списки медсестёр в текущем листе назначений

### ISSUE THREAD

**Issue by YuliYur** [rdn1983/cardiology#357]
Текущий лист назначений. Список дежурных медсестёр В списке присутствуют фамилии  врачей.

![image](https://user-images.githubusercontent.com/49306602/55639667-9705d000-57d2-11e9-8c28-c88354a28c72.png)

**Comment by rdn1983** [comment]
Список приведен в 
https://github.com/rdn1983/cardiology/wiki/%D0%93%D1%80%D1%83%D0%BF%D0%BF%D1%8B-%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2#%D0%94%D0%B5%D0%B6%D1%83%D1%80%D0%BD%D1%8B%D0%B5-%D0%BC%D0%B5%D0%B4%D1%81%D0%B5%D1%81%D1%82%D1%80%D1%8B

**Comment by ekaterinacat** [comment]
Правильно
