### ISSUE TITLE
Дневник Без КАГ в истории болезни отображается как журнал До КАГ

### ISSUE THREAD

**Issue by YuliYur** [rdn1983/cardiology#358]
В истории болезни, действия есть три дневника До КАГ, После КАГ и Без КАГ. при вводе дневника Без Каг , в истоии болезни появляется журнал ДО КАГ.

**Comment by LuliLa** [comment]
убран вообще такой вид журнала. сейчас можно создать журнал после каг, просто журнал, журнал отложенной КАГ.
