### ISSUE TITLE
Дежурный администратор

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#359]
![image](https://user-images.githubusercontent.com/40735638/55673551-0c949d80-58b2-11e9-8940-3a69fa512fa3.png)

**Comment by ekaterinacat** [comment]
Эта группа товарищей (обведена красным кружочком) не АДМИНИСТРАТОРЫ, а сотрудники отделения кардиореанимации

**Comment by rdn1983** [comment]
Поправил

![image](https://user-images.githubusercontent.com/38911304/55675296-35745d00-58c9-11e9-9593-ff71537cb489.png)

**Comment by ekaterinacat** [comment]
отлично
