### ISSUE TITLE
ЭКГ - 3

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#376]
![image](https://user-images.githubusercontent.com/40735638/55680176-cd506600-591e-11e9-9299-c28f3876543b.png)

**Comment by ekaterinacat** [comment]
После использования любых слов из шаблона ставить "ПРОБЕЛ", чтобы слова не сливались

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/447 - дубль
