### ISSUE TITLE
Ответственный врач, 1 

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#382]
![image](https://user-images.githubusercontent.com/40735638/55680501-e6f3ac80-5922-11e9-96f2-6ae9b26c3096.png)

**Comment by ekaterinacat** [comment]
Ответственный врач (по умолчанию) - кардиореаниматолог, который начал заполнять историю

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/55680520-16a2b480-5923-11e9-8ca8-75982c820e19.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/55680539-76995b00-5923-11e9-9f09-edf6ce70b14d.png)

**Comment by ekaterinacat** [comment]
Этот список не соответствует опции "ответственный врач". Ответственный врач - это врач кардиореаниматолог. 
1. По умолчанию должен предлагаться человек, начинающий писать историю
2. Или мы должны выбирать из списка "кардиореаниматологов"

**Comment by Bsska** [comment]
![image](https://user-images.githubusercontent.com/39027336/55909286-40d6c980-5be4-11e9-9a7e-98564a67bb1f.png)
 По умолчанию врач правильно указан, а список врачей неправильный. В списке должны быть только кардиореаниматологи

**Comment by YuliYur** [comment]
![image](https://user-images.githubusercontent.com/49306602/56077684-b8c11180-5de7-11e9-8c32-8d90a3728d94.png)
В списке ответственный врач (кардиореаниматолог) по умолчанию должен ставиться врач который принимал пациента

**Comment by LuliLa** [comment]
Исправила. Брался для отображения по умолчанию не кардиореаниматолог.
