### ISSUE TITLE
Назначения в шаблоне ОКС без подъема

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#383]
![image](https://user-images.githubusercontent.com/40735638/55680787-14daf000-5927-11e9-9239-31456bfef3d9.png)

**Comment by ekaterinacat** [comment]
Назначения отсутствуют

**Comment by ekaterinacat** [comment]
Ничего не поменялось

**Comment by rdn1983** [comment]
в процессе тестирования

**Comment by YuliYur** [comment]
Не совпадают шаблоны назначений
![image](https://user-images.githubusercontent.com/49306602/56078498-7ac8eb00-5df1-11e9-9edd-f246dd7c6111.png)
![image](https://user-images.githubusercontent.com/49306602/56078511-a8ae2f80-5df1-11e9-9d92-6a20814802d9.png)
