### ISSUE TITLE
Назначения в шаблоне "Квота"

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#384]
![image](https://user-images.githubusercontent.com/40735638/55680795-3340eb80-5927-11e9-89dc-afa16cff5801.png)

**Comment by ekaterinacat** [comment]
Назначения отсутствуют

**Comment by ekaterinacat** [comment]
Ничего не поменялось

**Comment by YuliYur** [comment]
В графе НАЗНАЧЕНО нет шаблонов
![image](https://user-images.githubusercontent.com/49306602/56078680-93d29b80-5df3-11e9-947e-5f6b1d19e8d0.png)
