### ISSUE TITLE
Назначения в шаблоне "расслоение аорты"

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#385]
![image](https://user-images.githubusercontent.com/40735638/55680805-73a06980-5927-11e9-9503-b02954369bc6.png)

**Comment by ekaterinacat** [comment]
Отсутствуют

**Comment by ekaterinacat** [comment]
Ничего не поменялось

**Comment by YuliYur** [comment]
В назначениях шаблоны появились, в Назначено пропали
![image](https://user-images.githubusercontent.com/49306602/56078445-c8912380-5df0-11e9-98b3-3ba0b0ff7818.png)
