### ISSUE TITLE
Исправление шаблонов в назначениях

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#389]
![image](https://user-images.githubusercontent.com/40735638/55680941-232a0b80-5929-11e9-9695-480ac743f5f6.png)

**Comment by ekaterinacat** [comment]
не работает

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/55863191-bc079380-5b82-11e9-9fc7-4d903cf8041b.png)

**Comment by ekaterinacat** [comment]
Ничего не поменялось

**Comment by YuliYur** [comment]
Нет шаблонов  в колонке НАЗНАЧЕНО
![image](https://user-images.githubusercontent.com/49306602/56078329-6a177580-5def-11e9-93c5-3c0ae714eae9.png)

В первичном осмотре назначения. Все шаблоны показывает, но... Есть шаблоны по диагнозам в левом столбце и есть шаблоны назначений тех же диагнозов внизу. Они не все совпадают
![image](https://user-images.githubusercontent.com/49306602/56078359-cd090c80-5def-11e9-8064-003be858acc0.png)

**Comment by LuliLa** [comment]
исправлено
