### ISSUE TITLE
Удобство выбора значений пульса, АД, частоты дыхания

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#391]
![image](https://user-images.githubusercontent.com/40735638/55681125-4c4b9b80-592b-11e9-83ea-d4b3188e14fb.png)

**Comment by ekaterinacat** [comment]
Необходимо все дневники подключить к возможному выбору по такой схеме

**Comment by LuliLa** [comment]
дубликат задачи. Для всех дневников сделали кнопку с таблицей выбора средних значений

**Comment by ekaterinacat** [comment]
Отлично
