### ISSUE TITLE
Разные дневники по умолчанию

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#393]
![image](https://user-images.githubusercontent.com/40735638/55681202-11963300-592c-11e9-9a02-9881eab1ab92.png)

**Comment by ekaterinacat** [comment]
У Юли есть 5 шаблонов дневников, которые нужно по УМОЛЧАНИЮ предлагать при необходимости использования нескольких дневников подряд. Дневники должны различаться, так же как фигуры на скрин-шоте

**Comment by LuliLa** [comment]
Уже сделано
