### ISSUE TITLE
Совместный осмотр

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#396]
![image](https://user-images.githubusercontent.com/40735638/55681380-9aae6980-592e-11e9-9323-c849b85267d7.png)

Исходник:  
![image](https://user-images.githubusercontent.com/40735638/55681362-62a72680-592e-11e9-80e9-25118df5c67e.png)

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/452 - дубль

**Comment by ekaterinacat** [comment]
Отлично. Получилось
