### ISSUE TITLE
Совместный обход

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#397]
![image](https://user-images.githubusercontent.com/40735638/55681399-dea16e80-592e-11e9-8924-aaab1fdaa64e.png)

![image](https://user-images.githubusercontent.com/40735638/55681395-d0535280-592e-11e9-9227-6d655751a027.png)

**Comment by ekaterinacat** [comment]
В совместном обходе нет возможности "залогиниться" или просто подписать начало дня, а также все последующие дни

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/451 - дубль

**Comment by ekaterinacat** [comment]
Отлично
