### ISSUE TITLE
Дневники по окончанию дня

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#400]
![image](https://user-images.githubusercontent.com/40735638/55681528-10ff9b80-5930-11e9-83f1-dcfc1d0a4116.png)

**Comment by ekaterinacat** [comment]
Если врач создал дневников больше, чем требуется (то есть при шаге "4 часа" дневники "переваливают" через 8.05), то
1. Или программа должна предупредить об этом (и врач тогда уменьшает количество дневников)
2. Или "шаг"  уменьшается до 2-3 часов между дневниками, чтобы не перевалить за 8.05 (то есть за конец рабочего дня

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/443 - дубль

**Comment by ekaterinacat** [comment]
Поняла, что заведена задача 443 с подробным описанием
