### ISSUE TITLE
Возможность убрать лишний дневник

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#401]
![image](https://user-images.githubusercontent.com/40735638/55681583-aac74880-5930-11e9-89b0-3c31e7f7a2e0.png)

**Comment by ekaterinacat** [comment]
Нужно добавить возможность убрать лишний дневник

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/443 - дубль

**Comment by ekaterinacat** [comment]
Жду реалиизации
