### ISSUE TITLE
Дневник на 8.05

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#402]
![image](https://user-images.githubusercontent.com/40735638/55681605-dd714100-5930-11e9-9d3a-94bbbd549165.png)

**Comment by ekaterinacat** [comment]
Дневник в 8.05 - самый главный дневник окончания дня. Он должен быть неформальным, то есть самым расширенным (из него потом могут браться  данные для "утреннего совместного осмотра") 
Нужно в дневник 8.05 добавить возможность выбора того, что именно войдет в него. 
Он чем-то должен походить на  "утренний совместный осмотр". То есть : там должны быть анализы, ЭКГ, рентген, КАГ ....

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/454 - дубль

**Comment by ekaterinacat** [comment]
Отлично. Жду реализации
