### ISSUE TITLE
Результаты обследований

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#403]
![image](https://user-images.githubusercontent.com/40735638/55681701-2e356980-5932-11e9-978a-b270d1ec7e11.png)

**Comment by ekaterinacat** [comment]
Результаты обследования заполнены (мы это видим по табличке)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/55681716-5329dc80-5932-11e9-9ae6-c3828e1a0b0b.png)

**Comment by ekaterinacat** [comment]
Как будто бы ничего и не заполняли

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/55681738-8ff5d380-5932-11e9-8315-95d0dc28a9cf.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/55681741-9ab06880-5932-11e9-9939-b58fa8b8ba4b.png)

**Comment by nik-novozhilov** [comment]
Это не ошибка.
1. Через пункт меню, например, "Действия - результаты обследования - ЭГДС" - добавляется новый анализ. Аналогично для других анализов.
2. Если необходимо открыть результат уже добавленного анализа, то в истории болезней пациента, на самом анализе нажать правой кнопкой мыши (ПКМ) - Редактировать. В таком случае открывается анализ, ранее заведенный.

**Comment by ekaterinacat** [comment]
отлично
