### ISSUE TITLE
Фраза "анализы в работе"

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#404]
![image](https://user-images.githubusercontent.com/40735638/55681765-d9deb980-5932-11e9-92b8-46ca9a0bfdd8.png)

**Comment by ekaterinacat** [comment]
В полях (зеленый и коричневый полукруг) даже при отсутствии данных нужно добавить строчку 
 "АНАЛИЗЫ И РЕЗУЛЬТАТЫ ОБСЛЕДОВАНИЙ - в работе

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/435 - дубль

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/56861697-0fb01480-69ac-11e9-9d3c-27419425b490.png)

**Comment by ekaterinacat** [comment]
Фраза "анализы в работе" - не добавлены
