### ISSUE TITLE
Выбор из врачей для постановки ВЭКС

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#407]
![image](https://user-images.githubusercontent.com/40735638/55867018-4a334800-5b8a-11e9-90c3-7011f496861a.png)

**Comment by ekaterinacat** [comment]
Нужно делать выбор из врачей ТОЛЬКО нашего отделения

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/428 - дубль
