### ISSUE TITLE
Выбор из врачей для манипуляции

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#408]
![image](https://user-images.githubusercontent.com/40735638/55867119-8ff01080-5b8a-11e9-9c31-11cbfff24cf1.png)

**Comment by ekaterinacat** [comment]
Нужно делать выбор только из врачей нашего отделения

**Comment by YuliYur** [comment]
Нужно чтобы во всех манипуляциях были врачи отделения кардиореанимации

![image](https://user-images.githubusercontent.com/49306602/56460382-821c6580-63aa-11e9-9310-2bede055ccd1.png)

![image](https://user-images.githubusercontent.com/49306602/56460392-a4ae7e80-63aa-11e9-8fa6-410faf080f59.png)

![image](https://user-images.githubusercontent.com/49306602/56460415-fa832680-63aa-11e9-9bc3-59f4b2b99a05.png)

![image](https://user-images.githubusercontent.com/49306602/56460418-0969d900-63ab-11e9-86fe-50f41330dab0.png)

![image](https://user-images.githubusercontent.com/49306602/56460423-22728a00-63ab-11e9-8d43-638487ed2cf5.png)

![image](https://user-images.githubusercontent.com/49306602/56460430-3a4a0e00-63ab-11e9-8fdd-52df732707a4.png)
