### ISSUE TITLE
Выбор для манипуляции

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#411]
![image](https://user-images.githubusercontent.com/40735638/55867432-24f30980-5b8b-11e9-8ab3-e0c975895bf5.png)

**Comment by ekaterinacat** [comment]
Выбор только из списка врачей нашего отделения

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/428 - дубль

**Comment by ekaterinacat** [comment]
отлично. Жду
