### ISSUE TITLE
Лишние анализы мочи создаются

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#426]
![image](https://user-images.githubusercontent.com/40735638/56149026-46515c80-5fb4-11e9-8107-e8e3be8950fd.png)

**Comment by ekaterinacat** [comment]
Ведет историю болезни Арсланбекова (это видно по подписям), однако в анализах мочи "вылез" Потехин...

**Comment by LuliLa** [comment]
Анализы мочи создаются ВСЕГДА при заведении первичного осмотра, убрать. Исправить заполнение врача для анализов мочи. Проверить все остальные анализы.

**Comment by ekaterinacat** [comment]
Про "мочу" - все хорошо

**Comment by ekaterinacat** [comment]
Периодически выползают другие врачи

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58368983-32770f80-7efd-11e9-9fb7-378c19d87765.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58368988-3dca3b00-7efd-11e9-9ea1-322522259b83.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58369013-69e5bc00-7efd-11e9-8a5d-ea71cc9b1013.png)

**Comment by ekaterinacat** [comment]
На это заведена отдельная задача
