### ISSUE TITLE
Ответственный врач - 7

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#430]
![image](https://user-images.githubusercontent.com/40735638/56150463-a8f82780-5fb7-11e9-94e5-1f453bd4439a.png)
![image](https://user-images.githubusercontent.com/40735638/56150449-a3024680-5fb7-11e9-8003-b3674ceeacd7.png)

**Comment by ekaterinacat** [comment]
Выбираем Арсланбекова ... Получаем Потехин

**Comment by LuliLa** [comment]
https://github.com/rdn1983/cardiology/issues/426

**Comment by nik-novozhilov** [comment]
Исправлено в рамках задачи #461 
при поступлении пациента некорректно сохранялись врачи в сессии пациента.
Сейчас исправлено, при поступлении новых пациентов, бланки будут формироваться корректно.

**Comment by ekaterinacat** [comment]
Отлично
