### ISSUE TITLE
Ошибка при печати листа назначений

### ISSUE THREAD

**Issue by rdn1983** [rdn1983/cardiology#433]
Пациент Петров-Водкин:
1. Действия - История болезни
2. Действия - Лист назначений
3. MsWord

Результат:
ошибка в программе

**Comment by rdn1983** [comment]
![image](https://user-images.githubusercontent.com/38911304/56275993-6d21a700-610a-11e9-9619-5cad3bb0cf19.png)

**Comment by rdn1983** [comment]
![image](https://user-images.githubusercontent.com/38911304/56276025-790d6900-610a-11e9-8875-9699eaf29b7c.png)

**Comment by ekaterinacat** [comment]
Все отлично
