### ISSUE TITLE
Дублирование шаблонов назначений в первичном осмотре

### ISSUE THREAD

**Issue by YuliYur** [rdn1983/cardiology#434]
![image](https://user-images.githubusercontent.com/49306602/56462868-18fd1800-63d3-11e9-8102-19e0e8416e82.png)

![image](https://user-images.githubusercontent.com/49306602/56462991-e3592e80-63d4-11e9-8641-a1ad26527786.png)

При смене шаблонов и сохранении, При повторном открытии начинается путаница в назначениях, они или удваиваются или из других шаблонов добавляются

**Comment by ekaterinacat** [comment]
Решили
