### ISSUE TITLE
Изменения в Дневниках после КАГ. Добавление контролов для выбора врача РХДМиЛ.

### ISSUE THREAD

**Issue by LuliLa** [rdn1983/cardiology#441]
В окне в групбоксе с названием: Осмотр ренгеноваскулярного хирурга (через 1 час после КАГ):
Отредактировать название групбокса(удалить то, что в скобках).
Добавить контролы для выбора даты/времени (по умолчанию поставить время +1 час от даты КАГ)
Добавить комбобокс для выбора врача. Заполнять комбобокс врачами РХДМиЛ.

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58369223-0e68fd80-7f00-11e9-9e1c-09d9a39b0223.png)

**Comment by ekaterinacat** [comment]
Не совпадает время, которое указывается на программе и время, которое выводится в ворде
