### ISSUE TITLE
Сопутствующие заболевания в первичном осмотре.

### ISSUE THREAD

**Issue by LuliLa** [rdn1983/cardiology#448]
При нажатии на кнопку с названием сопут. заболевания, оно добавляется в текстовое окно. Сама кнопка подсвечивается. Повторное нажатие убирает соотв. значение из текстового поля и выделение с кнопки. Текстовые поля-слушатели, на которые ведется воздействие: "Предварительный клинический диагноз", "Из сопутствующих заболеваний".

**Comment by rdn1983** [comment]
#462

**Comment by ekaterinacat** [comment]
Отлично
