### ISSUE TITLE
Замена слова

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#45]
![default](https://user-images.githubusercontent.com/40735638/42137103-3caac4dc-7d6f-11e8-8e81-56648fec9241.jpg)

**Comment by ekaterinacat** [comment]
Заменить слово "серология" на "инфекции"

**Comment by rdn1983** [comment]
![2](https://user-images.githubusercontent.com/38911304/42273085-d21d985a-7f90-11e8-8c62-34826363e302.PNG)

**Comment by ekaterinacat** [comment]
Отлично, правильно, спасибо

**Comment by ekaterinacat** [comment]
Отлично
