### ISSUE TITLE
Проблемы в Word версии Ежедневного осмотра

### ISSUE THREAD

**Issue by LuliLa** [rdn1983/cardiology#452]
1. не заполняется информация об экг. Остается в заполненном шаблоне {on_ekg}
2. убрать фразу: "Передан дежурному врачу"
3. текст шапки: Совместный обход... формируется их ФИО зам. отделения(берется из группы) и текущего врача(функционал по текущему врачу описан: https://github.com/rdn1983/cardiology/issues/451)

**Comment by nik-novozhilov** [comment]
Не воспроизводится.
Исправлено.

**Comment by Bsska** [comment]
Пункты 1 и 2 работают как надо.
Пункт 3 в шапке отображается лечащий врач как зав. кардиореанимацией
![image](https://user-images.githubusercontent.com/39027336/57988044-063d3800-7a92-11e9-8b9b-90af52ef831a.png)

**Comment by rdn1983** [comment]
По согласованию с Екатериной Виленовной, в шапке длжны отображаться 2 врача:
1. Зав отделения
2. Врач, который делает в текущий момент осмотр (в отчет попадает врач, который выбран в списке сверху)

![image](https://user-images.githubusercontent.com/38911304/58046235-680ea800-7b4d-11e9-9da8-761573bdd411.png)

**Comment by YuliYur** [comment]
Пропал крестик для добавления анализов крови, мочи и ЭКГ в первичном осмотре. Нет возможности добавить данные анализов. Так же и в ежедневном обходе нет возможности добавления анализов

![image](https://user-images.githubusercontent.com/49306602/58052697-33571c80-7b5e-11e9-8538-bd1b4ee2c186.png)

**Comment by ekaterinacat** [comment]
Отлично
