### ISSUE TITLE
Анализы.

### ISSUE THREAD

**Issue by LuliLa** [rdn1983/cardiology#454]
Разработать возможность множественной привязки анализов.
Один и тот же анализ может быть привязан к разным сущностям. Каждая сущность может быть привязана к разному виду анализов.

**Добавить возможность выбора анализов:**
Дневники(все виды)
Консилиум
Ежедневный обход
Предоперационный эпикриз(уже разработано)
Переводной эпикриз*
Выписной эпикриз*

\* - генерируются автоматически при выписке/переводе - https://github.com/rdn1983/cardiology/issues/453

**Comment by LuliLa** [comment]
Сделано во всех существующих формах. Формы для создания переводного и выписного эпикриза пока не сущ

**Comment by ekaterinacat** [comment]
Консилиум - прекрасно

**Comment by ekaterinacat** [comment]
Предоперационных эпикриз (заведена отдельная задача). В дообследовании - скобки

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58369094-67379680-7efe-11e9-9f33-7cde00638aca.png)

**Comment by ekaterinacat** [comment]
Ежедневный осмотр - отлично

**Comment by ekaterinacat** [comment]
Напряженно ждем - 
Переводной эпикриз*
Выписной эпикриз*

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58369120-cbf2f100-7efe-11e9-9afc-c1c1968dea8d.png)

**Comment by ekaterinacat** [comment]
Про дневники - заведена отдельная задача
![image](https://user-images.githubusercontent.com/40735638/58369182-7d922200-7eff-11e9-91dc-a669c3c5fcd2.png)
