### ISSUE TITLE
Совместный осмотр (продолжение 397)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#456]
![image](https://user-images.githubusercontent.com/40735638/56860522-22245100-69a0-11e9-82c8-ad25ff40b3fa.png)

**Comment by ekaterinacat** [comment]
То, что получилось 
![image](https://user-images.githubusercontent.com/40735638/56860542-6a437380-69a0-11e9-8bc3-98941317854a.png)

**Comment by ekaterinacat** [comment]
Исходник: 
![image](https://user-images.githubusercontent.com/40735638/56860608-15ecc380-69a1-11e9-9439-8adef064c091.png)

**Comment by ekaterinacat** [comment]
Врач РХМДиЛ встречается 1. При оформлении истории 2. Во всех случаях операции (КАГ) В предоперационном осмотре, в консилиуме, в дневниках после КАГ
Поэтому просто в дневниках, а тем более в утреннем совместном осмотре он НИКОГДА не встречается

**Comment by toolkas** [comment]
Изменена форма отчета совместного осмотра. 
См #452

**Comment by ekaterinacat** [comment]
Отлично
