### ISSUE TITLE
Данные первичного осмотра. Кнопки хронических заболеваний

### ISSUE THREAD

**Issue by rdn1983** [rdn1983/cardiology#459]
Сделать так, чтобы кнопки раздела хронических заболеваний отражали состояние текста в поле "Из сопутствующих заболеваний".

Первое нажатие кнопки - добавляет текст в поле "Из сопутствующих заболеваний" и кнопка остается активна, демонстрируя, что соответствующий ей текст добавлен. 
Если нажать кнопку повторно - соответствующий ей текст удаляется из поля "Из сопутствующих заболеваний" и сама кнопка становится неактивна.

**Comment by ekaterinacat** [comment]
Отлично
