### ISSUE TITLE
Неправильный лечащий врач в списке пациентов

### ISSUE THREAD

**Issue by rdn1983** [rdn1983/cardiology#461]
В списке пациентов в качестве лечащего врача отображается дежурный врач отделения РХМДиЛ, а нужно отображать дежурного кардиореаниматолога

**Comment by nik-novozhilov** [comment]
Исправил сохранение врачей при поступлении врачей, чтобы корректно формировались бланки.

**Comment by ekaterinacat** [comment]
Отлично
