### ISSUE TITLE
Вывод лечащего врача в списке "Ответственный врач" на форме первичного обхода.

### ISSUE THREAD

**Issue by nik-novozhilov** [rdn1983/cardiology#463]

**Comment by YuliYur** [comment]
В окне первичного осмотра нет списка ответственных врачей
![image](https://user-images.githubusercontent.com/49306602/57980800-859e1d80-7a38-11e9-99e8-a1168be1b90b.png)
![image](https://user-images.githubusercontent.com/49306602/57980810-a1a1bf00-7a38-11e9-82ce-cb20e742c6fb.png)

**Comment by toolkas** [comment]
Вернул
![image](https://user-images.githubusercontent.com/2483692/58027779-0d138b80-7b22-11e9-9b55-53d8dc0b4aab.png)

**Comment by ekaterinacat** [comment]
Отлично
