### ISSUE TITLE
Разделители слов для кнопок в первичных данных анализа

### ISSUE THREAD

**Issue by rdn1983** [rdn1983/cardiology#464]
Форма первичного осмотра, вкладка Первичные данные анализов. 
Подвкладка "ЭКГ".

При использовании кнопок групп Ритм, Девиация ST автоматически добавлять перед вставляемым текстом пробел и запятую, чтобы текст от двух последовательных нажатий кнопок не склеивался, например "Ритм синусовый" + "Депрессия"

**Comment by YuliYur** [comment]
Группы Ритм и Дивиация ST не склеиваются.  А шаблоны ЭКГ Инфаркт миокарда передней стенки ЛЖ и Инфаркт миокарда задней стенки ЛЖ склеиваются
![image](https://user-images.githubusercontent.com/49306602/57981646-c1d67b80-7a42-11e9-8f38-a43b62404ff2.png)

**Comment by rdn1983** [comment]
Уточним у Е.В информации по деталям склейки после проверки

**Comment by ekaterinacat** [comment]
Отлично. Но с этим справились, но сейчас в следующей задачке уточню пожелания
