### ISSUE TITLE
В окне Констатация смерти список всех врачей, Должен быть список кардиореаниматологов. и по умолчанию лечащий врач.

### ISSUE THREAD

**Issue by YuliYur** [rdn1983/cardiology#466]
В списке врачей в окне констатация смерти должен быть список только  кардиореаниматологов. По умолчанию сразу лечащий врач кардиореаниматолог.
![image](https://user-images.githubusercontent.com/49306602/57982026-0adcfe80-7a48-11e9-9860-2f1a67cdec90.png)
![image](https://user-images.githubusercontent.com/49306602/57982064-98205300-7a48-11e9-956b-b57c0d35a714.png)

**Comment by ekaterinacat** [comment]
Отлично, Принимается
