### ISSUE TITLE
Ошибка № 2 при открывании "журнал до КАГ"

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#485]
![image](https://user-images.githubusercontent.com/40735638/58242671-e6d73100-7d57-11e9-979a-17a60d98c7c6.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58242738-053d2c80-7d58-11e9-8df0-70ade37a4810.png)

**Comment by ekaterinacat** [comment]
При этом журнал, строчкой выше, открывается 
![image](https://user-images.githubusercontent.com/40735638/58242783-18e89300-7d58-11e9-8259-2bbd30585ac0.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58242833-2f8eea00-7d58-11e9-9127-6c2d42b1578c.png)

**Comment by ekaterinacat** [comment]
Журнал, строчной ниже, тоже открывается

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58242904-53eac680-7d58-11e9-8d01-c991856e9bd4.png)

**Comment by rdn1983** [comment]
Ошибка старых данных

**Comment by ekaterinacat** [comment]
Отлично
