### ISSUE TITLE
Титул (добавление полиса ОМС)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#52]
![default](https://user-images.githubusercontent.com/40735638/42137437-cea4013c-7d74-11e8-8f1d-c58a3581996d.jpg)

**Comment by ekaterinacat** [comment]
Ниже СНИЛСА нужно добавить номер полиса ОМС

**Comment by ekaterinacat** [comment]
Вчера, в описания титула, я просила добавить паспортные данные, число и где выдали. В остальном - отлично

**Comment by LuliLa** [comment]
Являются ли паспортные данные обязательными к заполнению?

**Comment by ekaterinacat** [comment]
Да, но можно их заполнять "немного отсроченно". Эти данный вносятся в документы"согласие ... ", протоколы. Было бы удобно иметь их заполенными. Но при этом важно иметь возможность переходить к следующим этапам заполнения истории, если они не внесены


>Четверг, 19 июля 2018, 10:08 +03:00 от Yulia <notifications@github.com>:
>
>Являются ли паспортные данные обязательными к заполнению?
>—

**Comment by ekaterinacat** [comment]
Снилс... полис... - отлично

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43072669-881cfb1c-8e7f-11e8-9f7e-9e86e24f1687.jpg)

**Comment by ekaterinacat** [comment]
Убрать из "первоочередной необходимости в заполнении" = номер истории, вес, рост

**Comment by ekaterinacat** [comment]
В остальном - великолепно выглядет... Хочется, чтобы заработало

**Comment by LuliLa** [comment]
А в чем не работает добавление нового пациента? Опишите, пожалуйста

**Comment by ekaterinacat** [comment]
Если не заполнено поле "номер истории болезни" , то невозможно продолжать заполнять историю дальше.... То есть просьба убрать поле "номер истории" из первоочередных заполнений
--
Отправлено из Mail.Ru для Android понедельник, 23 июля 2018г., 15:49 +03:00 от Yulia  notifications@github.com :

**Comment by LuliLa** [comment]
Исправлено.

**Comment by ekaterinacat** [comment]
Спасибо


>Вторник, 24 июля 2018, 23:34 +03:00 от Yulia <notifications@github.com>:
>
>Исправлено.
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

Екатерина Кошкина
