### ISSUE TITLE
Титул (обозначение койки)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#53]
![default](https://user-images.githubusercontent.com/40735638/42137479-ad03720a-7d75-11e8-8987-36c5b6799911.jpg)

**Comment by ekaterinacat** [comment]
Обозначить койко место (две цифры)

**Comment by LuliLa** [comment]
![image](https://user-images.githubusercontent.com/6269330/42399567-f7123084-8176-11e8-9551-16c038590cc8.png)

**Comment by ekaterinacat** [comment]
Годится
--
Отправлено из Mail.Ru для Android пятница, 06 июля 2018г., 23:47 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
Отлично.
