### ISSUE TITLE
Совместный осмотр

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#532]
Нужно в совместном осмотре иметь возможность выбрать то, что там будет вставлено

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58373709-2a3dc500-7f3b-11e9-9375-0b1f09065bbe.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58373733-93bdd380-7f3b-11e9-8a2a-bdbf12afec15.png)

**Comment by ekaterinacat** [comment]
Все вкладки активный (то есть во вкладках в красных кружках есть информация), которая не выбирается "как объект" при формировании итогового документа

**Comment by ekaterinacat** [comment]
Однако, в "ворд" все эти документы попадают

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58373744-e5fef480-7f3b-11e9-802d-a15e95831ffd.png)

**Comment by LuliLa** [comment]
с помощью кнопки "..." можно выбрать анализы из истории болезни, которые еще не были добавлены в текущий ежедневный осмотр. т.е. то, что окно выбора пустое говорит о том, что или вы уже все возможные анализы выбрали или еще не создавали. Судя то кол-ву вкладок на скрине - вы уже все анализы из истории добавили в ежедневный осмотр. При этом при создании нового ежедневного осмотра вы можете повторно все анализы привязать и к нему тоже. Кнопка с плюсиком нужна для того, чтобы не выходя из ежедневного осмотра сразу создавать и автоматически привязывать новый анализ к ежедневному осмотру. (на случай, если ни один из выбранных не подходит или просто забыли создать заранее)
