### ISSUE TITLE
Дневники (отложенные), 1. Не вписывается ЧСС

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#533]
![image](https://user-images.githubusercontent.com/40735638/58373763-1f376480-7f3c-11e9-9297-8ba49de7ff7b.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58373772-3a09d900-7f3c-11e9-9a0e-63e2b357c874.png)

**Comment by LuliLa** [comment]
дубль 536. в 536 исправила проблему для всех дневников вида НЕ_КАГ
