### ISSUE TITLE
Отложенная КАГ, 2 . Не пишется ЧСС

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#534]
![image](https://user-images.githubusercontent.com/40735638/58373787-6a517780-7f3c-11e9-9f5c-a1330ae93442.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58373795-966cf880-7f3c-11e9-911f-e3a90c94eaa7.png)

**Comment by LuliLa** [comment]
дубль 536. Исправила в 536 для всех дневников НЕ_КАГ
