### ISSUE TITLE
Отложенная КАГ, 3 . Не пишется ЧСС

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#535]
![image](https://user-images.githubusercontent.com/40735638/58373806-ca481e00-7f3c-11e9-8fa3-9d7ff26a7236.png)

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/58373819-fa8fbc80-7f3c-11e9-8a0c-b813cc99a7a3.png)

**Comment by LuliLa** [comment]
дубль 536
