### ISSUE TITLE
Вкладка "анализы"

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#54]
![default](https://user-images.githubusercontent.com/40735638/42137526-64ddd06e-7d76-11e8-9122-d7ed14943d42.jpg)

**Comment by ekaterinacat** [comment]
Вкладку с ФИО нужно убрать

**Comment by LuliLa** [comment]
Окно было заменено окном с  полной историей болезни

**Comment by ekaterinacat** [comment]
Принимается. Отлично
