### ISSUE TITLE
Анализы

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#55]
![default](https://user-images.githubusercontent.com/40735638/42137572-2a68ff8e-7d77-11e8-94e2-f201b01ddc2e.jpg)

**Comment by ekaterinacat** [comment]
Переименовать "анализы за последний месяц" на "анализы за настоящую госпитализацию"

**Comment by LuliLa** [comment]
Окно было заменено окном с полной историей болезни. Этих фильтров в новом окне нет.

**Comment by ekaterinacat** [comment]
отлично. Принимается
