### ISSUE TITLE
ЭКГ

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#57]
![default](https://user-images.githubusercontent.com/40735638/42137632-47bc3636-7d78-11e8-93a9-074dcc236227.jpg)

**Comment by ekaterinacat** [comment]
Из вкладки "экг" убрать все лишнее (перечернуто желтым)

**Comment by ekaterinacat** [comment]
Лучше совсем убрать вкладку ЭКГ при поступлении, тогда все остальное (желтое) само уберется
![default](https://user-images.githubusercontent.com/40735638/42137660-10caf594-7d79-11e8-888c-c1e3acd5797b.jpg)

**Comment by LuliLa** [comment]
![image](https://user-images.githubusercontent.com/6269330/42321601-370a6fc8-8062-11e8-8153-d81d062d3ee1.png)

**Comment by LuliLa** [comment]
Все ли нравится в окне? Все подходит?

**Comment by ekaterinacat** [comment]
Да, смотрится красиво. 
Замечания: 
1. Из этой вкладки нужно убрать названия "КАГ, ЭГДС", так как они уже есть в других вскладках
2. В этой же вкладке хочется увидеть шаблоны "инфарктов" (я их присылала как пожелания "скриншот" из интернета)
3. Там, где есть подзаголовок "девиация", нужно добавить "Девиация ST"
4. В этой же закладке нужно ввести графы а) "ЭКГ в динамике" б) ЭКГ текущее 

Спасибо


>Четверг,  5 июля 2018, 14:46 +03:00 от Yulia <notifications@github.com>:
>
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

Екатерина Кошкина

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/42825980-f5079310-89eb-11e8-98d8-a51c8c9dbda0.png)

**Comment by ekaterinacat** [comment]
Во вкладке "ЭКГ" создать подвкладку "Шаблоны" ЭКГ, куда перенести данные этой таблицы. Врач, должен иметь возможность "кликнув" на любую клеточку левого  столбца в поле "ЭКГ" получить данные из 2 и 3 столбца.... и наоборот. "Кликнув на "2 и 3 столбцы" получить в поле ЭКГ текст "переднеперегодочный инфаркт" 
![default](https://user-images.githubusercontent.com/40735638/42826673-a3ba3d3a-89ed-11e8-9aa9-d1471fa63efb.jpg)

**Comment by ekaterinacat** [comment]
Если плохо понятно, то объясню по телефону. Спасибо

**Comment by ekaterinacat** [comment]
![-1](https://user-images.githubusercontent.com/40735638/42826759-de933b6e-89ed-11e8-8a1a-bc543bdc6d30.jpg)

**Comment by ekaterinacat** [comment]
Уменьшите пожалуйста размер этого поля, там обычно не более 2х строчек

**Comment by ekaterinacat** [comment]
![-2](https://user-images.githubusercontent.com/40735638/42826994-55f2de1c-89ee-11e8-92ea-4be46c655cd2.jpg)

**Comment by ekaterinacat** [comment]
Нужно создать возможность добавлять и просматривать ЭКГ в динамике

**Comment by LuliLa** [comment]
Комментарии по пунктам:
1. Из этой вкладки нужно убрать названия "КАГ, ЭГДС" - Убрано
2. В этой же вкладке хочется увидеть шаблоны "инфарктов" (я их присылала как пожелания "скриншот" из интернета) - есть отдельная таска, она не была в релизе поэтому ее еще не сделала. Будет сделано в скором времени в рамках той таски.
3. Там, где есть подзаголовок "девиация", нужно добавить "Девиация ST" - исправлено
4. В этой же закладке нужно ввести графы а) "ЭКГ в динамике" б) ЭКГ текущее - добавила в новую таску

Уменьшите пожалуйста размер этого поля, там обычно не более 2х строчек - уменьшила

**Comment by ekaterinacat** [comment]
Прекрасно. Спасибо
--
Отправлено из Mail.Ru для Android четверг, 19 июля 2018г., 23:34 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
![1](https://user-images.githubusercontent.com/40735638/43070432-8038bbf4-8e78-11e8-8071-685df4732760.jpg)

**Comment by ekaterinacat** [comment]
Эта просьба не сделана

**Comment by ekaterinacat** [comment]
![3](https://user-images.githubusercontent.com/40735638/43070623-04282ae4-8e79-11e8-870a-cb4a585f2414.jpg)

**Comment by ekaterinacat** [comment]
не сделано

**Comment by ekaterinacat** [comment]
Спасибо.


>Вторник, 24 июля 2018, 23:27 +03:00 от Yulia <notifications@github.com>:
>
>Для просмотра нескольких видов анализов - необходимо разделять каждый вид анализа на отдельное окно.Это в рамках этой таски я сделать не могу. Остальные пожелания учла
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

Екатерина Кошкина

**Comment by ekaterinacat** [comment]
Отлично. Принимается
