### ISSUE TITLE
Создание возможности добавление анализов

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#60]
![default](https://user-images.githubusercontent.com/40735638/42173229-05b6b6f8-7e27-11e8-83f7-14e72a47b968.jpg)

**Comment by LuliLa** [comment]
Распишите подробнее, пожалуйста.

**Comment by LuliLa** [comment]
чтобы не заводить анализы через меню, на форме сделать кнопку добавления еще панельки с промежуточными анализами

**Comment by ekaterinacat** [comment]
Список "коротких", или "обязательных" анализов:
Гемоглобин, Лейкоциты, Тромбоциты, Креатинин, КФК, МВ-КФК

**Comment by ekaterinacat** [comment]
В длинном списке нужно добавить "СОЭ" и Убрать "хлор" из всех анализов
