### ISSUE TITLE
Анализы мочи - 1 

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#61]
![default](https://user-images.githubusercontent.com/40735638/42173674-8584e5b6-7e28-11e8-93ea-cfd706f89bd2.jpg)

**Comment by ekaterinacat** [comment]
Из списка анализов мочи убрать ненужные (отмеченные желтым цветом) параметры

**Comment by LuliLa** [comment]
![image](https://user-images.githubusercontent.com/6269330/42394017-5842dc2a-8161-11e8-905a-17997458d6b4.png)

**Comment by ekaterinacat** [comment]
Можно ли в этих графах при отсутствии данных при выведении на печать печать, писать " в работе"
--
Отправлено из Mail.Ru для Android пятница, 06 июля 2018г., 21:12 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
Спасибо. Анализы мочи - "радуют глаз". Наше пожелание сохранятся, если данные не внесены, то писать при выведении в ворд «в работе»
