### ISSUE TITLE
Создание новых вкладок

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#63]
![default](https://user-images.githubusercontent.com/40735638/42174138-f5312e78-7e29-11e8-8433-23caab3f133f.jpg)

**Comment by ekaterinacat** [comment]
Создать вкладки:
1. ЭКГ
2. КАГ
3. Анализы крови/мочи
4. Рентген, ЭГДС
5. Холтер, СМАД, ФВД
6. КТ/МРТ

**Comment by LuliLa** [comment]
У нас же есть уже вкладки ЭКГ, анализы крови и анализы мочи, рентген, эгдс? их надо доработать? Какое наполнение должно быть у вкладок: 
УЗИ/ЭХО (добавить какие-то поля на вкладку Узи?)
Холтер, СМАД, ФВД (добавить какие-то поля на вкладку Холтер, АД мон)
КТ/МРТ (отделить от рентгена?)
Консультанты(это не вкладка заключение специалистов?)

**Comment by ekaterinacat** [comment]
Не актуально
