### ISSUE TITLE
Создание отдельной вкладки КАГ (коронарография)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#65]
![default](https://user-images.githubusercontent.com/40735638/42174836-3625272a-7e2c-11e8-8e77-a9a95a6b8089.jpg)

**Comment by LuliLa** [comment]
![image](https://user-images.githubusercontent.com/6269330/42394362-8f5def5a-8162-11e8-8bbc-e4472d4546ba.png)

**Comment by LuliLa** [comment]
Посмотрите на окошко. Все ли так, как хотелось?

**Comment by ekaterinacat** [comment]
Отлично выглядит. Скажите пожалуйста, можно ли предусмотреть возможности добавления новых коронарографий, в том случае если вдруг больному делается повторные коронарографии Спасибо
--
Отправлено из Mail.Ru для Android пятница, 06 июля 2018г., 21:21 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
Да, очень хорошо
--
Отправлено из Mail.Ru для Android пятница, 06 июля 2018г., 21:22 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
Прекрасно. 
Хочется иметь дополнительное поле, которое позволит добавлять новые коронарографии, которые делают (не так часто, но бывает) одному и тому же больному
