### ISSUE TITLE
Создание отдельной вкладки (рентген)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#66]
![default](https://user-images.githubusercontent.com/40735638/42174938-92f61446-7e2c-11e8-9d8c-c1fbcae558d9.jpg)

**Comment by ekaterinacat** [comment]
Поле, отмеченное фиолетовым, отнести во вкладку "Рентген".

**Comment by LuliLa** [comment]
![image](https://user-images.githubusercontent.com/6269330/42397318-20891a80-816e-11e8-8400-02967f95775e.png)

**Comment by LuliLa** [comment]
разделила на 2 вкладки.

**Comment by ekaterinacat** [comment]
Спасибо. Отлично. Все правильно
--
Отправлено из Mail.Ru для Android пятница, 06 июля 2018г., 22:44 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
Очень хорошо. Спасибо. Ввести "активное" предложение текущей даты, чтобы не впечатывать вручную
