### ISSUE TITLE
Разделение вкладки КТ/МРТ и ренген

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#67]
![default](https://user-images.githubusercontent.com/40735638/42175131-30a2ef52-7e2d-11e8-856b-1b6207fe3f8f.jpg)

**Comment by LuliLa** [comment]
Дубликат задачи 66.

**Comment by ekaterinacat** [comment]
Разделите пожалуйста эти вкладки. Одна вкладка рентген. Вторая кладка коты и морти 1 кладка для 2 класса КТ и МРТ
--
Отправлено из Mail.Ru для Android пятница, 06 июля 2018г., 22:46 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
Отлично. Вкладки прекрасно выглядят. Обычно данные вносят в день исследования, поэтому сделайте так, пожалуйста, чтобы "автоматически" предлагалось текущее число.
