### ISSUE TITLE
Вкладка ЭКГ-6 (замена подчеркивания на тире)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#74]
![-6](https://user-images.githubusercontent.com/40735638/42177059-ef039478-7e33-11e8-9f21-35812dcf79ec.jpg)

**Comment by rdn1983** [comment]
![1](https://user-images.githubusercontent.com/38911304/42272954-69503f76-7f90-11e8-92ec-9fc30e8d51e1.png)

**Comment by ekaterinacat** [comment]
Класс...

**Comment by ekaterinacat** [comment]
Прекрасно
