### ISSUE TITLE
КАГ-2 (время начала)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#77]
![-2](https://user-images.githubusercontent.com/40735638/42179080-608c4e8a-7e3b-11e8-8b75-d5b45cb69359.jpg)

**Comment by ekaterinacat** [comment]
Активно предлагать время "начало КАГ" через полчаса после поступления пациента в стационар

**Comment by LuliLa** [comment]
А дату КАГ какую ставить? текущую или дату приемки пациента?

**Comment by ekaterinacat** [comment]
Через 30 минут после приемки и с возможностью корректировки даты
--
Отправлено из Mail.Ru для Android четверг, 05 июля 2018г., 09:49 +03:00 от Yulia  notifications@github.com :

**Comment by LuliLa** [comment]
Про время я поняла. Дату тогда ставлю тоже дату приемки, даже если сейчас +n дней. Возможность корректировки будет)

**Comment by ekaterinacat** [comment]
Да, правильно. Спасибо
--
Отправлено из Mail.Ru для Android четверг, 05 июля 2018г., 10:03 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42829949-137f165e-89f3-11e8-8465-03a2f44038b5.jpg)

**Comment by ekaterinacat** [comment]
Не могу проверить.... Задача, чтобы время КАГ было через полчаса после поступления в стационар

**Comment by ekaterinacat** [comment]
Закрываем. Все хорошо
