### ISSUE TITLE
КАГ-4 (данные КАГ)

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#79]
![-4](https://user-images.githubusercontent.com/40735638/42179265-ec46022c-7e3b-11e8-85a6-a2d7e473f71d.jpg)

**Comment by ekaterinacat** [comment]
Осуществить перенос данных КАГ с базы данных другого отделения

**Comment by LuliLa** [comment]
Это необходимо будет сделать перед стартом эксплуатации?

**Comment by ekaterinacat** [comment]
В общей компьютерной сети нашей больницы есть возможность заходить в папки других отделений. Мой вопрос был следующий - можно ли прописать "путь" автоматического скачивания информации по больным из папок другого отделения?

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42333839-7a227824-8084-11e8-88fb-d461503d88bd.jpg)

**Comment by toolkas** [comment]
Задача будет разделена на более мелкие. Закрыто по согласованию с Екатериной Виленовной
