### ISSUE TITLE
КАГ, дневники после

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#84]
![default](https://user-images.githubusercontent.com/40735638/42180345-8eb8311c-7e3f-11e8-9874-d1c9b0f1249b.jpg)

**Comment by ekaterinacat** [comment]
Не работает

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42805556-c5e55efa-89b4-11e8-9843-85b6ff9dfc07.jpg)

**Comment by ekaterinacat** [comment]
Сюда впервые (после входного диагноза) вписывается вручную уточненный диагноз после КАГ (коронарография). Этот диагноз "транслируется" потом бесконечное число раз. Предлагаю его назвать "диагноз после КАГ".

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42805681-201a54de-89b5-11e8-9991-6286a57fe9ef.jpg)

**Comment by ekaterinacat** [comment]
Используя эти две кнопки мы в дневники должны иметь возможность вносить данные о ритме. Эти данные вносятся в каждый дневник

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42805848-8ac8bc76-89b5-11e8-91fa-975c1509ec78.jpg)

**Comment by ekaterinacat** [comment]
Эти данные вносятся в каждый дневник

**Comment by ekaterinacat** [comment]
![2](https://user-images.githubusercontent.com/40735638/42805969-ebae2044-89b5-11e8-8cc3-21dc10ae8516.jpg)

**Comment by ekaterinacat** [comment]
В том случае, если выбран исходно (цифра 1) НЕПРАВИЛЬНЫЙ РИТМ, то в окне 3, должно появиться "трепетание предсердий. 
Если выбран "ПРАВИЛЬНЫЙ" РИТМ, то в окне 3 должно появиться "синусовый ритм"

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42806177-77a114ee-89b6-11e8-87f0-d2f61ffef0b0.jpg)

**Comment by ekaterinacat** [comment]
Эти дневники "типовые" должные появляться "автоматически" в этих окнах

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42806252-b2dc58de-89b6-11e8-9b93-85d4da91ca9e.jpg)

**Comment by ekaterinacat** [comment]
Мы должны иметь возможность не выводить на печать эти дневники (кнопка "скрыть" дневники"

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42806341-f3294898-89b6-11e8-9409-49ff281ebac9.jpg)

**Comment by ekaterinacat** [comment]
я уже формулировала просьбу по "случайном" распределении данных пульса и давления. я пришлю табличку, которую я мечтаю иметь

**Comment by ekaterinacat** [comment]
[Консилиум КАГ квота.docx](https://github.com/rdn1983/cardiology/files/2200979/default.docx)
[Консилиум ОКС без подъёма.docx](https://github.com/rdn1983/cardiology/files/2200980/default.docx)

**Comment by LuliLa** [comment]
т.е. после КАГ стабильно только 4 дневника заводится?
Я заметила что тексты , которые вы на скрине выделили как " типовые" немного друг от друга отличаются. Их такими и сделать?

**Comment by ekaterinacat** [comment]
Да, Вы правы, чуть-чуть пусть отличаются
--
Отправлено из Mail.Ru для Android четверг, 19 июля 2018г., 23:47 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43069153-164d6a3a-8e75-11e8-8169-5ecc1d2e9dca.jpg)

**Comment by ekaterinacat** [comment]
Убрать секунды

**Comment by ekaterinacat** [comment]
![1](https://user-images.githubusercontent.com/40735638/43069344-821f79ba-8e75-11e8-9690-1ca71fd5bdde.jpg)

**Comment by ekaterinacat** [comment]
Убрать зависимость ритм "правильный"... "неправильный" на все последующие дневнике... То есть сохранять возможность в каждом дневнике "автономно выбирать нужный ритм. 
Важно!!! При исправлении одного поля ... не исправлять все последующие дневники

**Comment by ekaterinacat** [comment]
![2](https://user-images.githubusercontent.com/40735638/43069524-fdfe7342-8e75-11e8-9948-d2a85c20745e.jpg)

**Comment by ekaterinacat** [comment]
В дневник 8.05 добавить начало "За прошедшие сутки состояние больного стабилизировалось"

**Comment by ekaterinacat** [comment]
![4](https://user-images.githubusercontent.com/40735638/43069698-728020a8-8e76-11e8-92d6-cb83cc9cc5d2.jpg)

**Comment by ekaterinacat** [comment]
При нажатии кнопки "скрыть" нужно скрывать этот дневник

**Comment by ekaterinacat** [comment]
![5](https://user-images.githubusercontent.com/40735638/43069829-d7aed1b8-8e76-11e8-91fd-9e5bf4c579c7.jpg)

**Comment by ekaterinacat** [comment]
"автоматически" предлагать время через час, после поступления

**Comment by ekaterinacat** [comment]
![6](https://user-images.githubusercontent.com/40735638/43069929-1478ee30-8e77-11e8-9b02-51c9dc5f1a7b.jpg)

**Comment by ekaterinacat** [comment]
![6](https://user-images.githubusercontent.com/40735638/43069982-36941ac6-8e77-11e8-9bf6-54082140248a.jpg)

**Comment by ekaterinacat** [comment]
Автоматически корректировать время (через час, после предыдущего дневника)

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43166170-88b3612c-8f9e-11e8-939c-44fc85e7a72c.jpg)

**Comment by ekaterinacat** [comment]
Внести "диапозоны давления и пульса" для хаотичного, автоматического занесения данных в соответствующие поля

**Comment by LuliLa** [comment]
Сделано все, кроме: Нет осознания того что писать и в какой момент в поле монитор для осмотра в 8-05. Добавить такие-же кнопки?

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43187332-cab208ca-8ff9-11e8-9f66-c63e33527240.jpg)

**Comment by ekaterinacat** [comment]
Пожелание - при нажатии на кнопку "скрыть" должно исчезать весь заведенный дневник. 
Это позволит: 1.  не путать, что выйдет на печать, а что нет. 2. Съэкономит место на экране

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43187448-16ae445a-8ffa-11e8-95e8-2770a59d9145.jpg)

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43187635-a69103aa-8ffa-11e8-9a56-41a74aae1235.jpg)

**Comment by ekaterinacat** [comment]
нет времени

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43187693-d2addbb6-8ffa-11e8-833e-2a353fa2bab0.jpg)

**Comment by ekaterinacat** [comment]
Кнопки выбора давления, пульса, частоты дыхания должно быть "общей" на все дневники. Это позволит съэкономить место на экране

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43187844-4a73e94c-8ffb-11e8-9319-fc9834355dd1.jpg)

**Comment by ekaterinacat** [comment]
При "единовременном" заполнении дневников поле "ритм" как правило един для всех. Необходимо оставить возможность редактирования этого поля, если в этом будет необходимость

**Comment by ekaterinacat** [comment]
![8](https://user-images.githubusercontent.com/40735638/43188218-4664f566-8ffc-11e8-8222-e48b3ee70735.jpg)

**Comment by ekaterinacat** [comment]
![jpg](https://user-images.githubusercontent.com/40735638/43188349-8d77156a-8ffc-11e8-906c-15726572ff90.jpg)

**Comment by ekaterinacat** [comment]
Спасибо Вам большое. Восхищены Вашим мастерством
