### ISSUE TITLE
Еще раз повтор групп и членов консилиума

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#85]
![default](https://user-images.githubusercontent.com/40735638/42180466-1494a018-7e40-11e8-9a5d-9d5019d51585.jpg)

**Comment by ekaterinacat** [comment]
Не работает

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42804612-248e2886-89b2-11e8-8c5c-5d9d1f632c73.jpg)

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42804685-613744c0-89b2-11e8-8933-490c46ef6b1c.jpg)

**Comment by ekaterinacat** [comment]
1. Каждой группе "дежурный администратор ...", "кардиореаниматолог" соответствует список фамилий, из которых мы должны иметь возможность выбирать (этот список я пришлю
2. Наиболее часто используемые фамилии *зав отделения, зам. главного врача по терапии должны сразу "предлагаться" по умолчанию
3. Фамилия врача кардиореаниматолога должна "автоматически соответствовать ФИО врача, который стал заводить историю болезни

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42804915-04302bd8-89b3-11e8-9fe9-ead194d6dbbd.jpg)

**Comment by ekaterinacat** [comment]
Цель должна автоматически предлагаться. Однако, нужно иметь возможность ее менять, в зависимости от задач

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42805032-5f8ae0fe-89b3-11e8-8b5e-f153d938f044.jpg)

**Comment by ekaterinacat** [comment]
Диагноз в консилиуме должен быть копирован из "первичного осмотра"

**Comment by ekaterinacat** [comment]
[Консилиум КАГ квота.docx](https://github.com/rdn1983/cardiology/files/2200987/default.docx)
[Консилиум ОКС без подъёма.docx](https://github.com/rdn1983/cardiology/files/2200988/default.docx)

**Comment by ekaterinacat** [comment]
Вот так "Финально" должен в ворде выглядеть консилиум

**Comment by ekaterinacat** [comment]
**Список врачей отделения кардиореанимации:** 
Арсланбенкова Серминаз Махмудовна (Арсланбенкова С.М.)
Горячева Елена Владимировна (Горячева Е.В.)
Кошкина Екатерина Виленовна (Кошкина Е.В.)
Беспалова Юлия Эдуардовна (Беспалова Ю.Э.)
Миронова Елена Александровна (Миронова Е.А.)
Докторова Марина Викторовна (Докторова М.В.)
Балханова Анна Юрьевна (Балханова А.Ю.)
Баграмова Юлия Анатольевна (Баграмова Ю.А.)
Генералова Ольга Александровна (Генералова О.А.)
Щербакова Светлана Владимировна (Щербакова С.В.)
Кустова Татьяна Юрьевна (Кустова Т.Ю.)


**Врачи отделения РХМДиЛ :**
Самочатов Денис Николаевич, заведующий (Самочатов Д.Н.)
Комков Артем Андреевич (Комков А.А.)
Миленькин Борис Игоревич (Миленький Б.И.)
Потехин Дмитрий Александрович (Потехин Д.А.)
Мостовой Игорь Владимирович (Мостовой И.В.)
Шестов Д.В.

**Врачи отделения анестезиологии**  

Костыря Ю.Е.
Данченко О.И.
Ерошин Н. И.
Магидин Д. В. 
Шиганова А. М. 
Капитанов А. Н. 
Казамбаев Е. А. 

**Зам. главного врача по терапи**и - Арефьев А.А
**Зав. центра анестезиологии и реанимации** - Шкуратова Н.В.
**Зав. центра хирургии** - Покровский К.А.

**Дежурные администраторы** - 

Арефьев   А.А.
--
Алекперов С.Ф.
Горбунов А.Л.
Горячев В.И.
Додица А.Н.
Зинухов А.Ф.
Иванов А.Э.
Иванов Г.И.
Казамбаев Е.А.
Кисель Д.Ю.
Клименко А.А.
Конев Д.Е.
Костылев Г.Н.
Костыря Ю.Е.
Лоскутников М.А.
Магомедов Х.Р.
Мартынов П.А.
Пейкер А.Н.
Покровский К.А.
Резепов Н.А.
Релин В.Е.
Семенов А.Ю.
Семченко В.И.
Соболев В.В.
Шандалин В.А.
Ширшов И.А.
Юрьев А.А.

**Comment by ekaterinacat** [comment]
В каждом разделе, в соответствии с задачей, мы должны иметь возможность выбрать нужного нам человека.

**Comment by LuliLa** [comment]
Автовыбор врача в соответствии с ролью пока сделать нет возможности. Надо менять схему. Перенесу в другую таску. Автозаполнение диагноза и цели сделала. Начала работать с шаблонами. начала по консилиуму уже можно посмотреть. Надо будет только уточнение какие именно анализа крови,экг и т.д. должны попадать в документ? Просто последние?

**Comment by ekaterinacat** [comment]
Я прислала шаблон документа, в котором есть  все параметры, который там желательно иметь в консилиуме.  Уточню: данные анамнеза (То есть как поступил в больницу, что болит, на что жаловался раньше), жалобы На текущий момент,  анализы, экг, текущее состояние. То есть все индивидуальные данные этого больного которые есть на момент написания консилиума
--
Отправлено из Mail.Ru для Android воскресенье, 22 июля 2018г., 00:09 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
1. и 2. - Добавать время
3. Добавить кнопку "-", скрыть
4.  Последний дневник " 8.15. За время .... "  на странице фиксирован, как первых два дневника


>Воскресенье, 22 июля 2018, 0:22 +03:00 от Yulia <notifications@github.com>:
>
>Closed  #85 .
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

Екатерина Кошкина

**Comment by ekaterinacat** [comment]
![1](https://user-images.githubusercontent.com/40735638/43067955-a78c35b6-8e71-11e8-9b10-8a3217fd818b.jpg)

**Comment by ekaterinacat** [comment]
1. Текст из вставки "цель оперативного пособия" не должен переходить в диагноз. ... Только место этого текста пока нет (я забыла, зачем он нужен), пока его не надо никуда переносить
2. В поле "диагноз" выносится диагноз из первичного осмотра
![default](https://user-images.githubusercontent.com/40735638/43068102-1d44e28a-8e72-11e8-8a2e-d215c9751b45.jpg)
:

**Comment by ekaterinacat** [comment]
В поле "диагноз" выносится диагноз из первичного осмотра - обведен зеленым

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43068208-76febf62-8e72-11e8-9a96-6c5167511ddb.jpg)

**Comment by ekaterinacat** [comment]
Создать кнопку "скрыть" либо "убрать" члена консилиума

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43068827-2cd9ccf4-8e74-11e8-9d94-a2cf0ecd6637.jpg)

**Comment by ekaterinacat** [comment]
Переименовать зав отделением рентгенхирургии в "зав. отделения  РХМДиЛ

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/43068945-808f3b2c-8e74-11e8-87dc-fc235486d3fd.jpg)

**Comment by ekaterinacat** [comment]
Добавить члена консилиума (со списком соответствующих сотрудников
"дежурный врач отделения РХМДиЛ

**Comment by ekaterinacat** [comment]
Ура! Получилось?

**Comment by Bsska** [comment]
![default](https://user-images.githubusercontent.com/39027336/45931335-877d1300-bf75-11e8-984f-20ea0aebdfb3.png)

**Comment by Bsska** [comment]
в следующем релизе можно будет посмотреть

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/48972071-9abf6400-f034-11e8-86bf-b87ad7f8485b.png)

НЕ сделано

**Comment by LuliLa** [comment]
Сделала, но в группу дежурных кардиореаниматологов сейчас пока включена только Генералова Ольга. Кого еще включить?

**Comment by ekaterinacat** [comment]
Абсолютно правильно, все врачи отделения кардиореанимации и есть "дежурные кардиореаниматологи"

**Comment by ekaterinacat** [comment]
![image](https://user-images.githubusercontent.com/40735638/50346354-2ef0ee00-0543-11e9-91b5-ce2a25e0e8f8.png)

**Comment by ekaterinacat** [comment]
Список по группам, который есть в консилиуме перенести в прием пациента
![image](https://user-images.githubusercontent.com/40735638/50346510-a32b9180-0543-11e9-9ea2-b93516f966a3.png)
