### ISSUE TITLE
Выписка, титул

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#86]
![default](https://user-images.githubusercontent.com/40735638/42180625-978b9512-7e40-11e8-94d0-4af68c639ff8.jpg)

**Comment by LuliLa** [comment]
Напишите, пожалуйста, саму ошибку. Я не поняла по скриншоту

**Comment by ekaterinacat** [comment]
Хорошо. Сейчас сделаю
--
Отправлено из Mail.Ru для Android вторник, 03 июля 2018г., 11:10 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42813746-aaa642a6-89ca-11e8-9888-e5fce87ebb26.jpg)

**Comment by ekaterinacat** [comment]
Во вкладке выписка/перевод должно содержаться варианты выписки (домой, отказ, перевод)

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42813854-fd3d3d30-89ca-11e8-83d5-1da392e23811.jpg)

**Comment by ekaterinacat** [comment]
В этой вкладке должны быть даты, соответствующие нахождению в стационаре, с переносом этих дат в саму выписку

**Comment by ekaterinacat** [comment]
![default](https://user-images.githubusercontent.com/40735638/42813995-76df1ece-89cb-11e8-801d-c1399e58b545.jpg)

**Comment by ekaterinacat** [comment]
Внутри вкладки перевод/выписка создать вкладку "лист нетрудоспособности"

**Comment by ekaterinacat** [comment]
Предлагаю закрыть
