### ISSUE TITLE
Добавление списка сотрудников

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#87]
![default](https://user-images.githubusercontent.com/40735638/42224521-ee3dbadc-7ee2-11e8-906f-1b34b3769194.jpg)

**Comment by ekaterinacat** [comment]
В окошко добавить возможность выбора списка сотрудников

**Comment by LuliLa** [comment]
остальные сотрудники были загружены в базу

**Comment by ekaterinacat** [comment]
Хорошо. Ждём базу
--
Отправлено из Mail.Ru для Android пятница, 06 июля 2018г., 22:57 +03:00 от Yulia  notifications@github.com :

**Comment by ekaterinacat** [comment]
Я отдельно пришлю сотрудников всех отделений, можете ли их распределить из отделений, чтобы не тратить время на выбор из списка?! Спасибо

**Comment by ekaterinacat** [comment]
Список присылала

**Comment by ekaterinacat** [comment]
Повтор. Было в другой задачке
