### ISSUE TITLE
Добавление Цоликлона Д

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#88]
![default](https://user-images.githubusercontent.com/40735638/42224928-f42e4d84-7ee3-11e8-8dab-7665123a6f22.jpg)

**Comment by ekaterinacat** [comment]
Добавить "окошко" Цоликлоны анти-Д      Серия .......   Годен до ..................

**Comment by Bsska** [comment]
Добавлено

**Comment by ekaterinacat** [comment]
![-](https://user-images.githubusercontent.com/40735638/43991528-62736a98-9d77-11e8-9a19-466bc5f67938.jpg)

**Comment by ekaterinacat** [comment]
Исправить Анти В на Анти Д

**Comment by ekaterinacat** [comment]
Сделано
