### ISSUE TITLE
Коррекция листа назанчения

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#91]
![default](https://user-images.githubusercontent.com/40735638/42226264-342e262c-7ee7-11e8-98de-609b53edef66.jpg)

**Comment by LuliLa** [comment]
![image](https://user-images.githubusercontent.com/6269330/42523273-fa5eb5f8-8475-11e8-92d6-cc7b6176760f.png)

**Comment by ekaterinacat** [comment]
Отлично. Нужно, чтобы часто повторяющиеся персонажи (зав. отделение и клин. фармаколог) предлагались в списке активно, а ФИО доктора, который заполняет Историю, тоже высвечивалось первым

**Comment by ekaterinacat** [comment]
Добавления (дежур. врач..., м\с...) - внесены, остальные части задачи перенесем в 129 ... и т.д.

**Comment by ekaterinacat** [comment]
Предлагаю закрыть эту задачу, как сделанную
