### ISSUE TITLE
Добавить строчку - ПОКАЗАНИЯ к МАНИПУЛЯЦИИ

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#92]
![default](https://user-images.githubusercontent.com/40735638/42226802-8d1d7494-7ee8-11e8-85b1-c83a6375449f.jpg)

**Comment by LuliLa** [comment]
Как итоговая строка должна выглядеть?
1. Показания к манипуляции - Протокол торакацентоза
2. Протокол торакацентоза (Показания к манипуляции)

Другой вариант?

**Comment by ekaterinacat** [comment]
Меня смущает, что сейчас я не вижу реальную картину (в ворде), поэтому точно не могу понять какой вариант выбрать (протокол... Показания). Давайте оставим, как сделали Вы, а потом посмотрим и окончательно решим

**Comment by ekaterinacat** [comment]
Отлично. все хорошо
