### ISSUE TITLE
Показания к Манипуляции продолжение

### ISSUE THREAD

**Issue by ekaterinacat** [rdn1983/cardiology#93]
![default](https://user-images.githubusercontent.com/40735638/42227227-ada9d864-7ee9-11e8-82c9-173f418a5d1e.jpg)

**Comment by rdn1983** [comment]
Поменял слово "показания" на слово "Показания к манипуляции". По словам Ольги этого достаточно

**Comment by rdn1983** [comment]
![1111](https://user-images.githubusercontent.com/38911304/42288449-66d6ef46-7fc3-11e8-9298-ae5d73b09247.PNG)

**Comment by ekaterinacat** [comment]
Прекрасно. Можно ли в окошке после слова "катетеризирована" добавить возможность выбора "правая", "левая", "яремная", "подключичная" вены ?

**Comment by ekaterinacat** [comment]
Да, все правильно, " показания к манипуляции"
--
Отправлено из Mail.Ru для Android среда, 04 июля 2018г., 19:49 +03:00 от rdn1983  notifications@github.com :

**Comment by ekaterinacat** [comment]
Все хорошо
